### ISSUE TITLE
Application Logging and Metric Collection 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2077]
Necessary for ECMPS Beta. 
Ensure that the applications are logging in the proper JSON format required by the Kibana dashboard and Collecting Metrics that are important to the EPA 

- [ ] Google tags for CAMPD and ECMPS 
- [ ] API error Handling and Logging
   -Broken up by each API: 
- [ ] Determine what events and metrics as determined by the EPA's process and procedures
- [ ] Determine method to manage performance rate 

[Link to Required API Metrics and Structured Logs ](https://teams.microsoft.com/_#/files/Tech%20Team?threadId=19%3Ae3d4667412cc496f87be989d2f8ede67%40thread.skype&ctx=channel&context=App%2520Metrics&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FTech%252FApp%2520Metrics)
