### ISSUE TITLE
Update CAMPD Home page and Data home page URL and Meta Tags 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2181]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a CAMPD user I want  the webpages to have descriptive urls and meta tags so that I can understand what kind of information the page contains 

## Acceptance Criteria

Given that a user has accessed the CAMPD home page 
When the page renders 
Then the webpage url and meta tags in consistent with the [CAMPD Home Page Content Document 
](https://teams.microsoft.com/l/file/D507FF3D-D28C-4C98-9A67-F32C2F79C568?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F1-Main%20Menu%2F1-Home%2FCAMPD%20Home%20Page%20Content-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

Given that a user has accessed the Data Home page 
When the page renders 
Then the webpage url and meta tags are consistent with the  [Data Home Page Content Document ](https://teams.microsoft.com/l/file/1680B428-F051-43F5-91B6-6707EC2363F6?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F1-Main%20Menu%2F2-Data%2F1-%20Data%20Home%20Page%20Content%20-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [ ] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

[CAMPD Home Page Content Document 
](https://teams.microsoft.com/l/file/D507FF3D-D28C-4C98-9A67-F32C2F79C568?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F1-Main%20Menu%2F1-Home%2FCAMPD%20Home%20Page%20Content-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

[Data Home Page Content Document ](https://teams.microsoft.com/l/file/1680B428-F051-43F5-91B6-6707EC2363F6?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2F6-Content%20Documents%2F1-Main%20Menu%2F2-Data%2F1-%20Data%20Home%20Page%20Content%20-EPA%20CAMD-v1.0.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

## Testing
Test Case:[ TC481](https://epacamd.testquality.com/project/11428/plan/21067/test/313114)
Tester: @JanellC 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
@tlageman-epa The team had the bandwidth to pull this ticket into sprint 6.3. TC481 passed.
