### ISSUE TITLE
Handle select all functionality on the checklist component - Emissions filter logic 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#2228]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context for the specific functionality being developed (design, business rules, etc.)
- [x] Does this have a dev link been provided in the design?
- [x] Is this traceable to a feature, epic, or PI?

## User Story
As a custom data download user I want to be restricted from selecting non-applicable criteria from the checklists so that I can avoid producing a query with no results 

## Acceptance Criteria
Given that the filer logic is engaged
When the the checklist functionality is displayed
Then the user can not select or apply filter criteria for greyed out items

Given that the filter logic is engaged
When the "select all" functionality is selected on the checklist component
Then the system selects criteria that is not greyed out

Given that the filter logic is engaged
When the checklist functionality is displayed
Then the select all functionality is disabled for groupings that only contain greyed out criteria

### Development Notes
- select all functionality for the checklist component
- The scope of this ticket is for all emissions sub types  

### Does this Story require 508 Testing?
- [ ] Implementing a new authoring tool that will produce code / content for the application
- [ ] Implementing a 3rd party widget that will be part of the application
- [x] Adding new / updating custom functionality 
- [ ] Adding new / updating a page template
- [ ] Adding new / replacing existing functionality (unless the replacement has already passed 508 testing)
- [ ] Full Site Review prior to a scheduled EPA 508 review
- [ ] Planning a video that will appear on the application
- [ ] Producing a video that will appear on the application
- [ ] Producing Training materials
- [ ] Producing documents

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

1. The custom data download allows a user to select and apply filter criteria for items greyed out from the check list. Users can apply filter criteria for greyed out items by selecting the select all check box. 
![image.png](https://images.zenhubusercontent.com/5f5928c1045cffdce7ce89c3/3ef58f21-5f0a-4158-817f-f20f71df14cb)

## Testing
Test Case: [TC455 ](https://epacamd.testquality.com/project/11428/plan/21762/test/312237)
Tester: @JanellC 

508 Testing: 
Tester: @aprematta 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by JanellC** [comment]
TC455 passed @tlageman-epa . However, I did discover a defect where the "select all" functionality is disabled for months and quarters on the time period filter. I logged Bug: Handle Select All Functionality #2289 to track the changes.

**Comment by JanellC** [comment]
This ticket is ready for 508 testing @aprematta
