### ISSUE TITLE
EASEY In Authentication and Authorization 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#250]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as

-User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
Authenticate and authorize EASEY IN users so they can securely access their workspace and submit their facility's data

## Dependencies:

- [ ] Determine user roles (role, access, matrix)
- [ ] Determine authentication and authorization method
- [ ] Design for log in UI
- [ ] Dev environment set up 
- [ ] Developer/tester access established 

Outcome:
Able to call service and get a response 

Milestone: CDX accounts and account registration for the EASEY program needs to be available in PROD NLT August 2022 (integration with EASEY app out of scope until later date). 

1. Will need to migrate existing user accounts. EPA will need to determine how and which users will be migrated from CBS. 

## Context
CDX environment is set up
[Link to docs ](https://teams.microsoft.com/_#/files/Tech%20Team?groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23&threadId=19%3Ae3d4667412cc496f87be989d2f8ede67%40thread.skype&ctx=channel&context=CDX&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FTech%252FCDX)
Program = EASEY 
The list of roles is the complete list for now
Account request, registration, and role assignment/management will happen in CDX for initial development. Integrating these services into ECMPS is out of scope for the MP Beta.
CDX has a staging environment that the services can be hosted for the MP Beta. Can be accessible to the public. 
Will need different permissions for Beta. Anyone can be a Designated Rep for Beta. will wipe roles before we go to PROD. 
QUESTION: How will dev and test accounts be created? How can we have multiple roles available for testing and development? Is ID proofing turned on?
MyCDX, Inbox, Submission History - in scope
Payment History - out of scope
CDX is responsible for security compliance 
Will have an EASEY log in page. Custom EASEY look and feel.
