### ISSUE TITLE
Monitoring 

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#2735]
Updates to logging to integrate with Splunk
Develop alerts for critical infrastructure and processes

**Splunk**

- [ ] Integrate with Splunk

**Freshping**

- [ ] Develop Freshping Dashboard 

**General**

- [ ] Determine Performance Monitoring Triage Process
