### ISSUE TITLE
QA Table Migration 1-5

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3395]
- [x] AE_CORRELATION_TEST_RUN (covered by #3394)
- [x] AE_CORRELATION_TEST_SUM (covered by #3394)
- [x] AE_HI_GAS (covered by #3394)
- [x] AE_HI_OIL (covered by #3394)
- [x] AIR_EMISSION_TESTING (covered by #3394)
