### ISSUE TITLE
QA Table Migration 6-12

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3396]
- [x] APS_CODE (covered by #3394)
- [x] CALIBRATION_INJECTION (covered by #3394)
- [x] COMMON_STACK_TEST_CODE (covered by #3412)
- [x] FUEL_FLOW_TO_LOAD_BASELINE (covered by #3394)
- [x] FUEL_FLOW_TO_LOAD_CHECK (covered by #3394)
- [x] CYCLE_TIME_SUMMARY (covered by #3394)
- [x] FLOW_RATA_RUN (covered by #3394)
