### ISSUE TITLE
QA Table Migration 13-23

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3397]
- [x] GAS_COMPONENT_CODE (covered by #3412)
- [x] GAS_LEVEL_CODE (covered by #3394)
- [x] GAS_TYPE_CODE (covered by #3394)
- [x] GFM_CALIBRATION (covered by #3412)
- [x] GFM_CALIBRATION_DATA (covered by #3412)
- [x] HG_LME_DEFAULT_TEST_DATA (covered by #3412)
- [x] HG_LME_DEFAULT_TEST_SUMMARY (covered by #3412)
- [x] HG_LME_DEFAULT_TEST_RUN (covered by #3412)
- [x] ON_OFF_CAL (covered by #3394)
- [x] OP_DATE_CODE (covered by #3412)
- [x] PARAMETER_UOM (covered by MP module)
