### ISSUE TITLE
QA Table Migration 24-36

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3398]
- [x] PRESSURE_MEASURE_CODE (covered by #3394)
- [x] PROBE_TYPE_CODE (covered by #3394)
- [x] PROTOCOL_GAS (covered by #3394)
- [x] PROTOCOL_GAS_VENDOR (covered by #3394)
- [x] QA_CERT_EVENT (covered by #3394)
- [x] QA_SUPP_ATTRIBUTE (covered by #3394)
- [x] QUAL_TYPE_CODE (covered by MP module)
- [x] RATA (covered by #3394)
- [x] RATA_FREQUENCY_CODE (covered by #3394)
- [x] RATA_RUN (covered by #3394)
- [x] RATA_SUMMARY (covered by #3394)
- [x] RATA_TRAVERSE (covered by #3394)
- [x] REF_METHOD_CODE (covered by #3394)
