### ISSUE TITLE
QA Table Migration 48-62

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3400]
- [x] 	TEST_BASIS_CODE (covered by MP module)
- [x] 	TEST_CLAIM_CODE (covered by #3394)
- [x] TEST_EXTENSION_EXEMPTION (covered by #3394)
- [x] 	TEST_FREQUENCY_CODE (covered by #3412)
- [x] 	TEST_QUALIFICATION (covered by #3394)
- [x] TEST_REASON_CODE (covered by MP module)
- [x] 	TEST_RESULT_CODE (covered by MP module)
- [x] 	TEST_TYPE_CODE (covered by MP module)
- [x] TEST_SUMMARY (covered by MP module)
- [x] TRANS_ACCURACY (covered by #3394)
- [x] UNIT (covered by CAMPD Release 1.0)
- [x] UNIT_BT_TYPE (covered by MP module actually UNIT_BOILER_TYPE)
- [x] UNIT_CAPACITY (covered by MP module)
- [x] UNIT_DEFAULT_TEST (covered by #3394)
- [x] UNIT_DEFAULT_TEST_RUN (covered by #3394)
