### ISSUE TITLE
View Emissions Module Test Data Types

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#3784]
Defining an Emissions dataset/view

- [ ] Create a physical table to flatten and store the data
- [ ] Create a procedure to refresh the data by monitor plan and reporting period
- [ ] Add data entry in camdecmpsaux.dataset
- [ ] Add data entry in camdecmpsaux.datacolumn for each column to be returned

**Comment by annalbrecht** [comment]
At the ECMPS 2.0 ticket refinement meeting held on 2/13/24, Chris instructed us to close Uber Epics.
