### ISSUE TITLE
Review Existing Info Arch (As Is)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#392]
## Tasks
- [x] Review and record existing ECMPS monitoring plan information architecture (IA)
- [x] Review with Chris to make sure everything is captured

## Outcomes
- [x] A document that shows the existing architecture of the monitoring plan section of ECMPS

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit, 

This has been posted for your review. Some notes about this IA document: [ECMPS Monitoring Plan Data IA](https://xd.adobe.com/view/9c4447cf-5c2b-43e9-89b9-19405ee45556-c917/)

Information architecture (IA) identifies and defines site content and functionality. It also establishes the underlying organization, structure, and nomenclature that define the relationships between a site’s content and functionality.

This document covers only the Monitoring Plan section of the existing ECMPS tool. Pages and sections are indicated by grey, blue, and yellow boxes. Action-based links or functionality is indicated by green boxes. Notes about available fields under each section are indicated by a white box.

What I'm looking for from you is to make sure that everything in the Monitoring Plan Data section of ECMPS is covered in this document. If anything is incorrect or missing, please making comments in the comments section of the document.

I'll get started on the revision but I wanted to get this in your hands to double-check that I'm working off the correct structure.

Best,
Alex

CC: @MoAdeyoju, @karenhwwoo

**Comment by chrisgitsit** [comment]
Alex this looks good.  Can we talk briefly about the MP comments section? I think the current system could use some improvement.
