### ISSUE TITLE
Revise Info Arch (To Be)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#393]
## Tasks
- [x] Review and record information architecture (IA) for FACT
- [x] Develop a revised IA document using both ECMPS and FACT as reference points
- [x] Review document with Chris

## Outcomes
- [x] An IA document for the new EASEY-In monitoring plan tool

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit — I've posted the final information architecture (IA) document with links to the existing ECMPS IA as well as the revised IA for EASEY-In [here in the Emissioners Teams files](https://teams.microsoft.com/l/file/9D3C2994-5DD9-4DF9-A943-C5576737C829?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2FUI%20Design%2F01%20Information%20Architecture%20(IA)%2FEASEY-In%20Information%20Architecture-EPA%20CAMD-v1.3.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23).

This document outlines the process and purpose of creating an IA document. It also points out some important findings in the existing IA and some notable improvements to the revised IA. Please let me know if you have any questions.

Best,
Alex

CC: @MoAdeyoju @karenhwwoo @JorjaComer

**Comment by cvp-alexrobinson** [comment]
Per our conversation today (11/23/20) with @chrisgitsit @JorjaComer and @karenhwwoo — I have revised the new IA so "Rectangular Duct WAFs" and "Loads" are independent sections and no longer grouped. The URL is the same.

**Comment by cvp-alexrobinson** [comment]
@ibarra-michelle — I've included a legend in the IA documents.
[Current ECMPS IA](https://xd.adobe.com/view/13ab6c4d-1931-483d-bcdf-a0b63aa8a815-46f8/)
[Revised EASEY-In IA](https://xd.adobe.com/view/c6cac0f6-e16b-42f0-b98b-cf429934000b-9399/)

CC: @karenhwwoo
