### ISSUE TITLE
Create MP Wireframes for Viewing and Editing 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#394]
## Tasks
**Design wireframes for the following:**
- [x] EASEY-In Global (Navigation, sub-navigation, overall layout)
- [x] MPD - Facilities List
- [x] MPD - Facility - Methods
- [x] MPD - Facility - Unit Characteristics - Editing
- [x] MPD - Facility - No Data

**Additional tasks:**
- [x] Review with internal stakeholders
- [x] Revise wireframes as needed

## Outcomes
- [x] Establish layout and content hierarchy for viewing and editing monitoring plan data

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit — [Here is the link to the wireframe documents](https://xd.adobe.com/view/e437f5dd-42bd-4e96-9da5-db61cb952e9f-b164/) for your review. Let me know if you'd like to set up a brief walkthrough to review or if you would prefer to give me your feedback here. You can also make comments directly in the prototype in the comments tab.

Some notes about the prototype:

- It starts off on the facility selection screen. From there you can select "Open All Tabs" and then click on the first tab, "Power Plant."
- Now on "Monitoring Methods," you can click on any cell in the first row of methods to bring up the row editor.
- To navigate to other screens, use the "Section Navigator." Only "Unit Information", "Monitoring Methods" and "Monitoring Defaults" currently exist.
- You can always toggle between the "Select Facilities" and "Power Plant" tabs.

Best,
Alex

CC: @karenhwwoo @MoAdeyoju @JorjaComer
