### ISSUE TITLE
High-Fidelity Monitoring Plan UI Design

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#395]
## Tasks
**High-fidelity designs for the following screens:**
- [ ] MPD - Facilities List
- [ ] MPD - Facility - Methods & Supplemental Methods - Editing
- [ ] MPD - Facility - Unit Characteristics
- [ ] MPD - Facility - No Data

**Additional tasks:**
- [ ] Review with internal stakeholders
- [ ] Revise designs as needed

## Outcomes
- [ ] Establish product UI for viewing and editing monitoring plan data

**Comment by JorjaComer** [comment]
Validated wireframes from 2.1
