### ISSUE TITLE
Apportionment Processes for CAMPD

### ISSUE THREAD

**Issue by MaeganWood64** [US-EPA-CAMD/PI-1#3952]
**Overview**

The apportionment process produces the unit-level emissions data used in CAMPD by doing the following:
- Flattens the HI, SO2 Mass, NOx Mass, NOx Rate and CO2 Mass values reported in the ECMPS Derived Hourly Value table and the CO2 Mass values reported in the Daily Emission table into hourly rows containing each of the values, Operating Time, Load, SO2 and CO2 rates, and measured information for each of the parameters.
- Apportions values measured at stacks or pipes to the connected units

**The ECMPS 2.0 process should generally follow the ECMPS 1.0 process, and utilize the 1.0 details**.

**The ECMPS 1.0 apporitonment process involves the following apportionment tables in CAMDECMPS (CAMDBSP) and CAMDDMW (CAMDPUB):**

- **Monitor Hourly**: CAMDECMPS: **MONITOR_HOUR**  CAMDDMW: **HOUR_MONITOR_DATA**
- **Monitor Daily**: CAMDECMPS: **MONITOR_DAY**  CAMDDMW: **DAY_MONITOR_DATA**
- **Monitor Monthly**: CAMDECMPS: **MONITOR_MONTH**  CAMDDMW: **MONTH_MONITOR_DATA**
- **Monitor Quarterly**: CAMDECMPS: **MONITOR_QUARTER**  CAMDDMW: **QUARTER_MONITOR_DATA**
- **Unit Hourly**: CAMDECMPS: **UNIT_HOUR**  CAMDDMW: **HOUR_UNIT_DATA**
- **Unit Daily**: CAMDECMPS: **UNIT_DAY**  CAMDDMW: **DAY_UNIT_DATA**
- **Unit Monthly**: CAMDECMPS: **UNIT_MONTH**  CAMDDMW: **MONTH_UNIT_DATA**
- **Unit Quarterly**: CAMDECMPS: **UNIT_QUARTER**  CAMDDMW: **QUARTER_UNIT_DATA**
- **MATS Monitor Hourly**: CAMDECMPS: **MATS_MONITOR_HOUR**  CAMDDMW: **HOUR_MONITOR_MATS_DATA**
- **MATS Unit Hourly**: CAMDECMPS: **MATS_UNIT_HOUR**  CAMDDMW: **HOUR_UNIT_MATS_DATA**

Notes:

- The process performs the apportionment using the CAMDECMPS apportionment tables (actually the ECMPS Client version of the tables), and then moves the data to the CAMDDMW tables.
- The CAMDECMPS SO2, NOx and CO2 masses are in pounds.  For CAMDDMW, the CO2 mass is in pounds, but the SO2 and NOx masses are in tons, and additional columns exist that contain the SO2 and NOx pound values.  **The summing of mass values should occur using pounds values, not tons.**
- CAMPD currently only contains the "unit" version of the apportionment tables.  However, CAMD plans to implement the "monitor" version of the tables.
- MATS data are not aggregated to day, month nor quarter values.

**CAMDDMW also includes the following apportionment tables:**

- **ANNUAL_MONITOR_DATA**
- **ANNUAL_UNIT_DATA**
- **OZONE_MONITOR_DATA**
- **OZONE_UNIT_DATA**

**The following Reported Emission tables in CAMDECMPS contain the source data for apportionment:**

- **HRLY_OP_DATA**: Contains the operating time and load for each location and hour.
- **DERIVED_HRLY_VALUE**: Contains the heat input, SO2 Mass, NOx Mass, NOx Rate, and CO2 Mass rows for each location and hour.
- **DAILY_EMISSION**: Contains daily CO2 emissions for a location.  For apportionment, the daily emissions are divided equally for the operating hours for the location and day.

**The ECMPS 1.0 version involves the following steps:**

1. Pull the Reported Emissions data from **HRLY_OP_DATA**, **DERIVED_HRLY_VALUE** and **DAILY_EMISSION** tables, flattent the data into hourly rows, and store the row in **MONITOR_HOUR**.
2. For monitoring plans (MP) that contain a single unit, populate the **UNIT_HOUR** row for the unit and hour from the **MONITOR_HOUR** row for the unit and hour.
3. For other MP, populate the **UNIT_HOUR** for the unit nad hour based on the **MONITOR_HOUR** rows for all locations in the MP, and the connections between the locations in the MP.
4. Sum **MONITOR_HOUR** rows to produce **MONITOR_DAY** rows, **MONITOR_DAY** to produce **MONITOR_MONTH** rows, and **MONITOR_MONTH** to produce **MONITOR_QUARTER** rows.
5. Sum **UNIT_HOUR** rows to produce **UNIT_DAY** rows, **UNIT_DAY** to produce **UNIT_MONTH** rows, and **UNIT_MONTH** to produce **UNIT_QUARTER** rows.
6. Populate CAMDDMW tables from their matching CAMDECMPS tables.
7. Create or replace **ANNUAL_MONITOR_DATA** and **ANNUAL_UNIT_DATA** rows by summing **QUARTER_MONITOR_DATA** and **QUARTER_UNIT_DATA** rows respectively.
8. Create or replace **OZONE_MONITOR_DATA** and **OZONE_UNIT_DATA** rows by summing **MONTH_MONITOR_DATA** and **MONTH_UNIT_DATA** rows respectively.

**Complex Apportionment:**

Most apportionment occurs automatically based on the MP configuration.  However, complex configurations and some changing configurations require formulas to determine how to apportion data.  Those formulas are stored in the following tables on both the ECMPS 1.0 Host (CAMDECMPSAUX) and Client (ECMPS).

- APPORTIONMENT: Parent table that indicates the MP, begin quarter, and if it exists end quarter for the apportionment formulas.
- APPORTIONMENT_RANGE: Child table used to create separate formulas for distinct ranges for a monitoring plan.  Typically used when formulas are needed for a MP with configuration changes.
- APPORTIONMENT_DATA: Grandchild table that stores actual apportionment formulas.  Multiple rows may exist for an APPORTIONMENT_RANGE parent.  When that occurs the rows are ordered and all but the last contains a condition to determine whether it is the row used for the apportionment.  This usually provides the ability to apply different formulas based on which locations are operating.  Additionally, APPORTIONMENT_DATA allows the ability to indicate when a stack is a duct contributing to another stack for which the emissions should be reduced before being apportioned.

**Key ECMPS 1.0 Non-Table Objects**

- Application : **DM** Project (C#): Controls the apportionment process and performs the actual apportionment.
- Application : **DM.cUpdateEmissions** Class (C#): Calls delegates needed to interact with the database or methods similating the database for testing purposes.
- Application : **EmissionsReport.cUpdateEmissionsDb** Class (C#): Links the ECMPS.DB.cUpdateEmissions object to the supporting database objects and tables.
- Application : **EmissionsReport.cUpdateEmissionsDb.UpdateUnitHour** Method (C#): Bulk loads the apportioned hourly data into the **MONITOR_HOUR** and **MATS_MONITOR_HOUR** tables.
- Database    : **DmEm.UpdateInit**: Loads "monitor" apportionment tables and returns sets of data needed by the check engine to apportion data.
- Database    : **DmEm.UpdateSuccess**: Loads "unit" day, month and quarter apportionment tables.
- Database    : **DmEm.GatherMonitorHour**: Gathers hourly monitor data for the **MONITOR_HOUR** table.
- Database    : **DmEm.GatherMatsMonitorHour** Gathers hourly monitor data for the **MATS_MONITOR_HOUR** table.

Note that all apportionment related ECMPS 1.0 database objects are in the "DmEm" schema.

**Other Notes:**

- The new ECMPS 2.0 apportionment process will need to add a record the CAMDDMW.OP_YEAR table for each new year that is processed:
- - OP_YEAR - newly submitted year
- - ARCHIVE_IND - 0
- - HOURLY_DATA_IND - 1

**Needed Decisions:**
1. Determine whether the Check Engine DM Emission process should utilize a set of DM tables to perform the re-calculation process, or will use the target CAMDDMW tables directly.  Note that the NOXM
2. Determine whether the CAMPD emissions, whether in CAMDECMPS, CAMDDMW, or both should be deleted when an emission report is resubmitted, or just when the CAMPD emissions are reproduced.
3. Ensure that existing DM emissions are cleared for a submitted emission report,  This could occur as part of the DM Emissions job.

```[tasklist]
### Tasks
```

**Comment by MaeganWood64** [comment]
- Chris Deprioritized, focused on the Beta release and this will not be worked on until after march

**Comment by djw4erg** [comment]
## Programming Task Checklist

1.  **Create Tables** (CAMDECMPSMD):
      - [x] PDEM_REPORT_USER_CODE (from DM_EMISSIONS_USER_CODE)
2. **Create Tables** (CAMDECMPSAUX):
   - [x] PDEM_REPORT (from DM_EMISSIONS)
      - [x] PDEM_REPORT_USER (from DM_EMISSIONS_USER)
      - [x] PDEM_MATS_MONITOR_HOUR (from MATS_MONITOR_HOUR)
      - [x] PDEM_MATS_UNIT_HOUR (from MATS_UNIT_HOUR)
      - [x] PDEM_P75_MONITOR_HOUR (from MONITOR_HOUR)
      - [x] PDEM_P75_UNIT_DAY (from UNIT_DAY)
      - [x] PDEM_P75_UNIT_HOUR (from UNIT_HOUR)
      - [x] PDEM_P75_UNIT_MONTH (from UNIT_MONTH)
      - [x] PDEM_P75_UNIT_QUARTER(from UNIT_QUARTER)
3. **Create Stored Procedures and Functions**
   - [ ] DeleteUnitData (?)
   - [x] Get Apportionment Data as individual table functions
      - [x] GetApportionmentTable
      - [x] GetApportionmentRangeTable
      - [x] GetApportionmentDataTable
      - [x] GetApportionmentFormulaTable
      - [x] GetApportionmentConditionTable
      - [x] GetApportionmentSubtractiveTable
   - [x] UpdateFailure
   - [x] Update Init
      - [x] Update Reset
      - [x] Load Part 75 Monitor Hour
      - [x] Load MATS Monitor Hour
         - [x] is MATS Emission Report
         - [x] MATS MODC To Measure Code
         - [x] ~Scientific Notation To Float~
   - [x] Update Init Get Report Dates
   - [x] Update Init Location Information
   - [x] Update Init Report Period Information
   - [x] Update Init Location Type Counts
   - [x] Update Init Spanning Link Counts
   - [x] Update Init Active Link Counts
   - [x] Update Init CP LTFF Information
   - [x] Update Init Combined (P75 and MATS) Hourly Data
   - [x] UpdateSuccess
      - [x] LoadUnitDay
      - [x] LoadUnitMonth
      - [x] LoadUnitQuarter
4. Link Check Engine to Database
   - [ ] cUpdateEmissionsDb
      - [ ] GetFactorFormulaeArray
      - [ ] UpdateInit
5. Drop Check Engine Unused Methods
   - [ ] cUpdateEmissionsDb
      - [ ] UpdateInit_Setup
      - [ ] UpdateReset

**Comment by annalbrecht** [comment]
Testing of this ticket will occur in #6562.
