### ISSUE TITLE
Review Wireframe User Validation Feedback and Revisions (need by 12/22)

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#396]
## Tasks
- [x] Package wireframes for public-facing validation
- [x] Revise wireframes based on feedback, if applicable

## Outcomes
- [x] Validate wireframes through design reviews with ECMPS users
- [x] Revised and finalized wireframes for the new monitoring plan tool

## Revisions
- [x] Change dropdown names as follows: Monitoring Plans > Configurations; Monitoring Plan Sections > Sections
- [x] Add toggle within Configurations and Locations dropdowns to display/hide inactive/retired selections. The active selections appear first, inactive second (hidden by default). Include group labels above each section
- [x] Add an additional dropdown between “Configurations” and “Sections” called “Locations.” This will allow users to navigate between the individual locations within a configuration
- [x] Address large tables and scrolling
- [x] Add table-centric pagination
- [x] Address tab overflow

**Comment by cvp-alexrobinson** [comment]
@chrisgitsit — Wireframes have been exported as a PDF for archive purposes and [are available here](https://teams.microsoft.com/l/file/6953461C-A91F-4BDE-8F51-E48FC2F414E3?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pdf&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2FUI%20Design%2F02%20Wireframes%2FEASEY-In%20Wireframes.pdf&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23).

CC: @karenhwwoo  @JorjaComer @MoAdeyoju

**Comment by JorjaComer** [comment]
Validation will occur during 2.2. Updated sprint.

**Comment by cvp-alexrobinson** [comment]
## Revisions
- [ ] Add toggle within MP dropdown to display/hide inactive plans. The active monitoring plans first, inactive second (hidden by default). Include group labels above each section.
- [ ] When a configuration is selected from the “Monitoring Plans” dropdown, an additional dropdown will dynamically appear between “Monitoring Plans” and “Monitoring Plan Sections” called “Unit/Stack/Pipe.” This will allow users to navigate between units/stacks/pipes within a configuration.

**Comment by cvp-alexrobinson** [comment]
## Revisions
- [ ] Add toggle within MP dropdown to display/hide inactive plans. The active monitoring plans first, inactive second (hidden by default). Include group labels above each section.
- [ ] When a configuration is selected from the “Monitoring Plans” dropdown, an additional dropdown will dynamically appear between “Monitoring Plans” and “Monitoring Plan Sections” called “Unit/Stack/Pipe.” This will allow users to navigate between units/stacks/pipes within a configuration. 
- [ ] Address large tables and scrolling.

**Comment by cvp-alexrobinson** [comment]
@jwhitehead77, @addisgmichael — [Here's a new rough wire](https://xd.adobe.com/view/ca182076-d5e2-432d-9f50-c98aefb28d73-9f4b/) that addresses the following issues:
- Tab overflow (right arrow shifts right, left shifts left)
- Table scrolling (header row would be frozen, as well as the "add row" button, row count, and pagination)
- Row quantity (dropdown paired with keyword filter, proposed to be on every table)
- Table pagination (proposed to be on every table)
- New dropdown style with inactive/retired toggles

Let's take a look at this on Monday.

CC: @karenhwwoo @JorjaComer @MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
@karenhwwoo — [Here are the updated wireframes](https://xd.adobe.com/view/c2462d8e-32fd-447b-a9c1-4067176bc335-9715/). Only a few things function in the prototype... the new EPA web app template menus (header and footer); toggling between Select Facilities and Power Plant; and the facility dropdowns (Configuration, Locations, Section).

CC @JorjaComer @jwhitehead77 @MoAdeyoju
