### ISSUE TITLE
Emissions Module Data View Conversion and Load 

### ISSUE THREAD

**Issue by jwhitehead77** [US-EPA-CAMD/PI-1#4156]
Convert the following tables in the SQL Server client database to Postgres. These tables will need to be in the camdecmps and camdecmpswks schemas.

**Naming convention**
camdecmps.emission_view_<view-code>
camdecmpswks.emission_view_<view-code>

**Example**
[dbo].[EMISSION_VIEW_DAILYCAL] --> camdecmps.emission_view_dailycal
[dbo].[EMISSION_VIEW_DAILYCAL] --> camdecmpswks.emission_view_dailycal

**These tables are in the ECMPS Client SQL Server database**
- [ ] [dbo].[EMISSION_VIEW_ALL]
- [ ] [dbo].[EMISSION_VIEW_CO2APPD]
- [ ] [dbo].[EMISSION_VIEW_CO2CALC]
- [ ] [dbo].[EMISSION_VIEW_CO2CEMS]
- [ ] [dbo].[EMISSION_VIEW_CO2DAILYFUEL]
- [x] [dbo].[EMISSION_VIEW_DAILYCAL]
- [ ] [dbo].[EMISSION_VIEW_HIAPPD]
- [ ] [dbo].[EMISSION_VIEW_HICEMS]
- [ ] [dbo].[EMISSION_VIEW_HIUNITSTACK]
- [ ] [dbo].[EMISSION_VIEW_LME]
- [ ] [dbo].[EMISSION_VIEW_MASSOILCALC]
- [ ] [dbo].[EMISSION_VIEW_MATS_HCL]
- [ ] [dbo].[EMISSION_VIEW_MATS_HF]
- [ ] [dbo].[EMISSION_VIEW_MATS_HG]
- [ ] [dbo].[EMISSION_VIEW_MATS_SO2]
- [ ] [dbo].[EMISSION_VIEW_MATS_SORBENT]
- [ ] [dbo].[EMISSION_VIEW_MATS_WEEKLY]
- [ ] [dbo].[EMISSION_VIEW_MOISTURE]
- [ ] [dbo].[EMISSION_VIEW_NOXAPPEMIXEDFUEL]
- [ ] [dbo].[EMISSION_VIEW_NOXAPPESINGLEFUEL]
- [ ] [dbo].[EMISSION_VIEW_NOXMASSCEMS]
- [ ] [dbo].[EMISSION_VIEW_NOXRATECEMS]
- [ ] [dbo].[EMISSION_VIEW_OTHERDAILY]
- [ ] [dbo].[EMISSION_VIEW_SO2APPD]
- [ ] [dbo].[EMISSION_VIEW_SO2CEMS]

Convert the following procedures in the SQL Server client database to Postgres. These procedures will only need to be in the camdecmpswks schemas.

**Naming convention**
camdecmpswks.refresh_emission_view_<view-code>

**Example**
[ViewEmissions].[GridData_DAILYCAL] --> camdecmpswks.refresh_emission_view_dailycal

**These procedures are in the ECMPS client SQL Server database**
- [ ] [ViewEmissions].[Grid_Data_CO2DAILYFUEL]
- [ ] [ViewEmissions].[GridData_ALL]
- [ ] [ViewEmissions].[GridData_CO2APPD]
- [ ] [ViewEmissions].[GridData_CO2CALC]
- [ ] [ViewEmissions].[GridData_CO2CEMS]
- [x] [ViewEmissions].[GridData_DAILYCAL]
- [ ] [ViewEmissions].[GridData_HIAPPD]
- [ ] [ViewEmissions].[GridData_HICEMS]
- [ ] [ViewEmissions].[GridData_HIUNITSTACK]
- [ ] [ViewEmissions].[GridData_LME]
- [ ] [ViewEmissions].[GridData_MASSOILCALC]
- [ ] [ViewEmissions].[GridData_MATS_HCL]
- [ ] [ViewEmissions].[GridData_MATS_HF]
- [ ] [ViewEmissions].[GridData_MATS_HG]
- [ ] [ViewEmissions].[GridData_MATS_HG]
- [ ] [ViewEmissions].[GridData_MATS_SO2]
- [ ] [ViewEmissions].[GridData_MATS_SORBENT]
- [ ] [ViewEmissions].[GridData_MATS_WEEKLY]
- [ ] [ViewEmissions].[GridData_MOISTURE]
- [ ] [ViewEmissions].[GridData_NOXAPPEMIXEDFUEL]
- [ ] [ViewEmissions].[GridData_NOXAPPESINGLEFUEL]
- [ ] [ViewEmissions].[GridData_NOXMASSCEMS]
- [ ] [ViewEmissions].[GridData_NOXRATECEMS]
- [ ] [ViewEmissions].[GridData_OTHERDAILY]
- [ ] [ViewEmissions].[GridData_SO2APPD]
- [ ] [ViewEmissions].[GridData_SO2CEMS]
