### ISSUE TITLE
Create UI Pattern Library

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#428]
## Tasks

- [x] Design a UI pattern library that includes all UI components and instructions for usage
- [x] Review with existing stakeholders
- [x] Revise document as needed

## Outcomes

- [x] A living pattern library document for designer and front-end developer reference

**Comment by JorjaComer** [comment]
Completed
