### ISSUE TITLE
Determine level of effort to convert from SQL connector to Postgres connector

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#430]
## Tasks
- [x] Look through code to determine what changes are required 
- [x] Identify files and stored procedures where changes are required
- [x] Determine level of effort required to convert from SQL connector to Postgres connector 

## Outcomes
Files and stored procedures have been identified where changes are required

**Comment by SimeraHailu** [comment]
https://teams.microsoft.com/_#/files/TheEmissioners?threadId=19%3A56d336e3060849efa0557d379b78d9ca%40thread.skype&ctx=channel&context=Validation%2520Check%2520Engine%2520Analysis&rootfolder=%252Fsites%252FCAMDCVPTeam%252FShared%2520Documents%252FTheEmissioners%252FValidation%2520Check%2520Engine%2520Analysis
