### ISSUE TITLE
Develop UI to edit monitoring plan

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#453]
## User Story
As a user, I want to select a Facility's Monitoring Plan, so that I can make edits to it.

## Tasks
- [ ] Build new UI (restyle according to wireframes)
- [ ] Redo redux state to fit new data contract
- [ ] Modify selectors if applicable
