### ISSUE TITLE
Develop data service to edit monitoring plan

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#454]
## User Story
As a user, I want to select a Facility's Monitoring Plan, so that I can make edits to it.

## Tasks
- [ ] Create endpoint stubs with random static data
- [ ] Generate entities and DTOs (contracts)
- [ ] Create repository and wire the service to the database
