### ISSUE TITLE
Develop data service to view monitoring plan location and relationships

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#456]
## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Tasks
- [ ] Create endpoint stubs with random static data
- [ ] Generate entities and DTOs (contracts)
- [ ] Create repository and wire the service to the database
