### ISSUE TITLE
Develop UI to view monitoring systems

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#459]
## User Story
As a user I want to view production monitoring plan data so that I can look at real time data.

## Tasks
- [ ] Build new UI (restyle according to wireframes)
- [ ] Redo redux state to fit new data contract
- [ ] Modify selectors if applicable
