### ISSUE TITLE
EASEY UI: Global Navigation

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#503]
## Tasks
- [x] Develop a plan and a layout that shows where the EASEY-In platform will live on epa.gov and how users of both EASEY-In and -Out will navigate between the two platforms.

## Outcomes
- [x] Visual artifact resolving EASEY navigation
- [x] Internal review with EPA PO

**Comment by cvp-alexrobinson** [comment]
@karenhwwoo and @MoAdeyoju — Here's the global navigation user path document for your review: https://xd.adobe.com/view/f1f6e252-0782-4bd0-9f91-b78d4d5877d0-a4a5/

This document shows the two main paths a user would take to "end up" where we are in the wireframes (EASEY-In Dashboard > Workspace > Monitoring Plans). It also gives a draft outline of some of the levels and steps along the way. I'm hoping it will help start the conversation about the interplay between the two apps and where they live in the EPA ecosystem.

Please feel free to reach out with questions or you can comment directly in the XD document.

CC @staceyrenner

**Comment by MoAdeyoju** [comment]
Looks good to me, @cvp-alexrobinson but I will defer to @karenhwwoo for more specific feedback. Lets plan to show (or discuss with) @chrisgitsit and @ibarra-michelle the WIP during the UX weekly meeting on 12/14

**Comment by cvp-alexrobinson** [comment]
Thanks, @MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
This document has been uploaded to Teams under TheEmissioners > 00 Miscellaneous > [EPA EASEY Suite User Paths.pdf](https://teams.microsoft.com/l/file/6BD5319F-75CA-4E41-AF40-64CAD2CED008?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pdf&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FTheEmissioners%2FUI%20Design%2F00%20Miscellaneous%2FEPA%20EASEY%20Suite%20User%20Paths.pdf&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:56d336e3060849efa0557d379b78d9ca@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)
