### ISSUE TITLE
Review & Revise QA & Cert IA

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#505]
## Tasks
- [ ] Review and record existing QA & Cert information architecture (IA)
- [ ] Develop a revised IA document
- [ ] Review documents with Chris

## Outcomes
- [ ] A document that shows the existing architecture of the QA & Cert section of ECMPS
- [ ] An IA document for the new EASEY-In QA & Cert tool

**Comment by cvp-alexrobinson** [comment]
@davidkwartler this is new and slated for 2.4. I might need some help making sure it's organized appropriately
