### ISSUE TITLE
E-O Info Arch (create To Be)

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#545]
## Tasks
- [x] Develop information architecture (IA) document for EASEY-Out 
- [ ] Review documents with EPA 

## Outcomes
- [ ] An IA document for the new EASEY-Out

**Comment by tlageman-epa** [comment]
Alex, I know we have sort of discussed this in passing last Thursday at the UX weekly, but I wanted to note here that I would like to talk about this work at the refinement 12/16 and that we do not want anything based off AMPD, but rather the requirements we determined/shared. (first task on this ticket doesn't seem applicable). Thanks!

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — absolutely! EASEY-Out will be its own product defined by UXR and not by how AMPD currently works. We're on the same page. I also updated the tasks.

**Comment by cvp-alexrobinson** [comment]
@JorjaComer — [Here's the E-O Apportioned Emissions IA document](https://teams.microsoft.com/l/file/BE84AE25-D99D-427B-B93D-20BE9AA08EF5?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=pdf&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FDatateers%2FUI%20Design%2F01%20Information%20Architecture%20(IA)%2FEASEY-Out%20IA%20-%20Apportioned%20Emissions.pdf&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:f4349e2ba95e43f3b29e8208bc8f5d5f@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23) for your review. I'll be going over this in the demo as well.
