### ISSUE TITLE
E-O Sort/Filter: Create Wireframes

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#547]
## Preliminary Tasks
- [x] Identify and present UI design strategies/concepts/approaches to EPA
- [x] Get feedback and approval for a UI design strategy/concept/approach

## Tasks
- [x] Create wireframes for the hourly emissions sort/filter section of EASEY-Out
- [x] Review wireframes with EPA
- [x] Create a separate ZenHub task for revisions (if applicable)

## Design Assets
- [EASEY-Out Filter/Sort Wireframes v 1.2](https://xd.adobe.com/view/5b1e95b8-8e24-49d0-9a09-fa54e45ad485-0e4d/?fullscreen)

#### Stakeholders:
@tlageman-epa 
@JorjaComer
@MoAdeyoju

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa @kstetsyuk — Very very early link posted in the issue description. Wanted to share this little bit of progress.

Still playing around with things but here are some notable ideas and concepts:
- Date and Time section offers dates for comparison and an Operation Hours slider with an "All day" toggle.
- Live results appear alongside the filter/sort options for On-Demand Data (very much a work in progress). They are presented as a small narrative... the idea is a plain language sentence that perfectly describes the current query. This idea might be scalable into dynamic queries just based on plain language sentences like "2018 hourly emissions data from facilities in New Jersey." That might be a little pie in the sky.
- The query narrative presented in the wireframes introduces the concept of "Upwind." This could be something that is calculated from the average jetstream direction based on a starting point. Based on some of the comments from the UXR, folks may want to know which emitting facilities are polluting the air over their city. Upwind would give them those results.

CC @JorjaComer @MoAdeyoju

**Comment by tlageman-epa** [comment]
Hey Alex, just wanted to provide links to those two websites I mentioned in our last discussion (in 2020) where we talked about needing an exemption for the template header/banner and that the site would eventually include charts/graphs/maps/etc. 

https://www.airnow.gov/

https://ghgdata.epa.gov/ghgp/main.do

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Thanks so much for sharing these!

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — [Here are the design direction screens](https://xd.adobe.com/view/21b0f038-3b07-415b-ac01-7a2133f8fd08-74e3/) that will be guiding our conversation on today's call. There is a splash page that will lead you into the options, and an orange button in each option's nav bar that will navigate you between the four options. 

Some basic prototyping is included. For example, clicking buttons such as "Preview" or "Clear" will navigate you to additional screen views.

Please feel free to share with folks on the team before our call.

Best,
Alex

CC @MoAdeyoju @JorjaComer

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa and team—thanks for your time and feedback on the possible design directions. I will move forward with wireframes based on design direction **option two**. While I flesh these out, I will be sure to do the following:

- Account for additional data types, e.g. Allowance and Compliance
- Include very robust queries that show how the form would adapt to massive amounts of input

Please let me know if I missed anything.

Best,
Alex

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Hello and happy Friday! [Here is a link](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/e1ab33de-9d65-479a-9541-9464ab535800) to what I'm working on with the "active" form fields. I'm still working on the various states and making them interactive.

- **Dataset** lets users select from their desired dataset—limited to one selection
- **Time Period** lets users select a single or range of years, quarters, or days—with the option to select "Operating hours only"
- **Facility Information** includes two search fields with dynamic auto-complete based on input. One covers facility names, ORIS codes, and owner/operators. The other covers all location-based fields. This section also includes a multi-option select field that allows users to select multiple characteristics. This tag style could be extended to the search fields if multiple parameters can be selected.

More to come in the upcoming weeks. Have a great weekend!

CC @MoAdeyoju @JorjaComer

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson Thanks for sharing, this looks like good progress. Here are some thoughts:

-	**Dataset**: I think this is ok. Maybe the selections could be grouped so that there is Emissions, Allowance, and Compliance data types that separate the potential selections? Similar to the way the Facility one exists, except instead of Facility Name and Owner/Operator it would be Emissions, Allowance, and Compliance. The way it is mixed together (Hourly Emissions, Allowance, etc. is too confusing IMO)
-	**Time Period:** We hadn’t specifically decided that “Operating Hours Only” would be under time frame, but maybe that’s the best “group” that it fits into? We can leave it for now though. Also, I like that the user can see all the years selected, but I don’t want them to have to select every single one if they’re trying to get a lot? Maybe it could be a slider or something else? Curious your thoughts here.
- **Location:** We haven’t talked about filtering on any other location-based criteria except state, although I like the idea of filtering by county/zip code. So for now, let's stick to just filtering on state.
- **Multiple selects**:  We aren't sure how intuitive it is that the user would know they can select multiple states or facilities in their request. This will be a capability, so how can this be made clearer to the user?
-	**Unit Characteristics**: I think the high level looks good for the groups of controls, unit type and fuel type, however, Idk how this will look with all the values that can occur under each of those groupings. (Please see the Business Glossary for the tables that hold these values and let me know if you have any questions. I think Junie or Sejal could help you pull those from the data if needed) Maybe each criteria within the unit characteristics can have an expandable drop down if users want to select further?
-	**Required vs. Not required**: I want to see how this would look. I think we should indicate what is required and not and that for those that are not, if nothing is selected. Then everything is returned.

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Thanks so much for these! I've added some notes below...

- **Datasets:** I actually had that in my first version but went with a simple list. I'll try grouping these options.
- **Time Period:** One thing about these fields is they may change when a different dataset is selected, so I wanted to make sure that any change that happens dynamically happens under a dropdown, and not immediately visible on the form. That's why operating hours fall under the dropdown.
- **Location:** We can do that.
- **Multiple Selects:** I see your point—I'll see what I can do.
- **Unit Characteristics:** Jorja and I were talking about this today! If you'd like to go granular with the UC items, we can figure out a way to make that happen. I like your idea about being able to dig in more if you want to.
- **Required vs. Not Required:** Lots of folks in the UXR interviews mentioned wanting to just download "the big file." I wanted to accommodate that by just making the datasets required. This is definitely open to conversation and will be up to you all (with tech and bandwidth considerations in mind).

CC @JorjaComer @MoAdeyoju

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson 

- **Unit Characteristics**: I'd like to see how going granular would work. I need to check with EMB SMEs to see if keeping it high level is acceptable and can determine by COB Friday. The API accepts specific values vs. higher level groupings. @JorjaComer can we put in a backlog item that is "to discuss grouping inputs for unit characteristics filter criteria e.g., All Boilers, All turbines, etc."
- **Required vs. Not Required**: In the Business Glossary (BG) we have a column indicating whether or not a term is required for the UI. These would be the data type/dataset as you mentioned, and Time Period as well. For clarification, as listed in the BG, Operating Hours Only is _not_ required.

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — Thanks so much for your time this afternoon! The wireframes presented today are available in the card description if you'd like to take a look.

Based on our conversation, here are some updates that I'll make in advance of our conversation on Tuesday:

**Time Period**
- The date selector should just be a date picker (one for single, two for a range)—eliminating the need for "Date Span" and "All Years."
- Remove the date default, allowing the user to select a time period before moving forward.

**Facility Information**
- Remove the Owner/Operator search criteria from the facility dropdown.
- Rename facility dropdown to be, "Facility Name / ORIS Code." Split suggested fill categories up into "Facility Name" and "ORIS Code"
- Rename "Location" dropdown to be,  "State / Territory." Remove the category heading and the "Select all" option since that's already the default.
- Remove the "Select all" options from the "Unit Characteristics" dropdown headings, since "Select all" is already the default.

Please let me know if I captured everything.

CC @JorjaComer @MoAdeyoju

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson This looks good to me! Thanks for distilling it all down.

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson Hey Alex, couple additional notes after meeting with EMB folks today. Thanks and have a good weekend! 

- SO2 should be a subscript for the 2. Noticed it was a superscript in the Controls filter
- I confirmed that we want to keep the granularity of all the Unit Characteristics filters. So users should be able to select for all of say, SO2 Controls, but should also still be able to select for specific SO2 controls. Users do use this granularity. It is my understanding that you have it this way already, but just wanted to confirm. 
- We were also wondering how this might look if the data preview was below the filter criteria, so that it was on the same page? I'd be curious to see how users reacted to that as well as the way you currently have it with the pop-up. I think that might be valuable to have in the UX study to show the two options.
