### ISSUE TITLE
Test Only: Emissions Schema and DTO

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#5626]
The below tickets need to be tested:

- [ ] [Emissions Schema Updates for Import/Export #5602](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5602)

- [ ] [Emissions API Updates due to Emissions Schema Updates for Import/Export #5603](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5603)

- [ ] [Emissions API DTO Validation Updates #5604](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5604)
