### ISSUE TITLE
Test Only: MP Schema and DTO

### ISSUE THREAD

**Issue by mosesdeeCVP** [US-EPA-CAMD/PI-1#5628]
The below tickets need to be tested:

- [x] [MP Schema Updates for Import/Export #5596](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5596)

- [x] [MP API DTO Validation Updates #5598](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5598)

- [x] [MP API Updates due to MP Schema Updates for Import/Export #5597](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5597)

- [x] [Frontend: MP Schema Updates #5609](https://app.zenhub.com/workspaces/ecmps-prod-team-64623d2269329d0c96ba04f3/issues/gh/us-epa-camd/easey-ui/5609)

**Comment by mosesdeeCVP** [comment]
Updates were made, but some bugs still remain. These bugs will be handled in a future ticket.

**Comment by mosesdeeCVP** [comment]
Bugs:

There is a discrepancy between the excel and Reporting Document (SPAN-3). The excel says must be within the range of 0 and 9999999999. Reporting document says must be within the range of 500000 and 9999999999. Current error message says this as well. I believe schema example and excel need to be updated to reflect the document.
monitoringSpanData > mpfValue

Same as above:
["monitoringLocationData.0.rectangularDuctWAFData.0.[DEFAULT-80-D] - The [wafValue] for [Rectangular Duct Waf] is not within the range of valid values.  This value must be greater than 0 and less than 1." ],
Excel: Min 0 - Max 99.9999

**Comment by mosesdeeCVP** [comment]
Bug:

Error message is not appropriate for error. It is correct for negative, but not larger than acceptable amount of digits. Also does not show what the user is expected to enter:
monitoringSystemFuelFlowData > maximumFuelFlowRate

**Comment by mosesdeeCVP** [comment]
Bug:

Qualifications do not import as  they should. I am getting below error (Also check AnalyzerRange)(This seems to work fine on UI):
{
    "message": "[\"[IMPORT32-CRIT1-A] You have reported an AnalyzerRange record for a component with an inappropriate ComponentTypeCode.\",\"[IMPORT12-FATAL-A] You have reported a MonitorQualPercent record for a location with the Qualification Type Code not equal to PK, SK or GF. A MonitorQualPercent record should not be reported for qualification Codes other than PK, SK or GF.\",\"[IMPORT11-NONCRIT-A] A value has been reported for SO2Tons for the Monitor Qualification LME record #0. This field should be blank\",\"[IMPORT12-FATAL-B] You have reported a MonitorQualLME record for a location with the Qualification Type Code not equal to LMEA or LMES. A MonitorQualLME record should not be reported for qualification Codes other than LMEA or LMES.\",\"[IMPORT31-CRIT1-A] You have reported a System Fuel Flow record for a system that is not a fuel flow system. It is not appropriate to report a System Fuel Flow record for any other SystemTypeCode than OILM, OILV, GAS, LTGS, or LTOL.\",\"[IMPORT10-NONCRIT-A] An extraneous value has been reported for mpfValue in the span record for CO2. This value was not imported.\"]",
    "errorId": "9d0aa71e-4f79-40e6-80b7-d5a2a0ba83c8",
    "statusCode": 400
}
