### ISSUE TITLE
Research: Review MP Import Checks to determine if they ignore inactive records

### ISSUE THREAD

**Issue by acollad1** [US-EPA-CAMD/PI-1#5942]
- [ ] Add to MP import checks to only apply to active records (active records mean no end date on the record)
- [ ] Will need to be applied to all data types on the monitoring plan (default, etc.)
- [ ] Will still export all MP data active and inactive

**Comment by mosesdeeCVP** [comment]
Further updates need to be made to the DTOs. Development will continue to fix bug

**Comment by mosesdeeCVP** [comment]
Further discussion around this ticket needs to happen. From my understanding DTO checks will not be skipped only check service checks. This means most of the errors will fire anyway. There was a suggestion that DTO checks can be skipped as well, but that could lead to the unintentional addition of bad data into the system if Inactive data was changed by mistake and never checked. 

The initial facility used for testing this was "APS Saguaro Power Plant 1, 2, CS1"

**Comment by shahbazkhan1999** [comment]
@ergjustin will look into it

**Comment by ergjustin** [comment]
verified in DEV env

**Comment by ntknguyen** [comment]
I think the issues have not been addressed.  When trying to verify this is done, I encountered 32 errors.  Steps to reproduce:
1. Checkout APS Saguaro Power Plant config 1,2,CS1
2. Export MP data from historical
3. Import the exported file from step 2 including the inactive records
4. Received 32 error(s)

![Image](https://github.com/US-EPA-CAMD/easey-ui/assets/17596531/138cf4e7-f7c3-4184-ac93-353f2b7bac96)

**Comment by lgiannini1** [comment]
Testing for Saguaro blocked by #6186

**Comment by annalbrecht** [comment]
Need a list of import checks to test. Blocked by #6104

**Comment by djw4erg** [comment]
# Review of this Issue

## ECMPS 1.0 Background

ECMPS 1.0 contains three types of checks: import, screen, and report (submission).  Import checks perform minimal checks including ensuring that required rows for XML data exists in the database, non-mutable values are the same in the XML and database when a matching row exists in the database, the records for units and stacks referenced in Unit Stack Configuration exists in the XML, and preventing unexpected Monitor Qualification child records based on the Qualification Type Code.  The import checks will allow the import of data that screen and report (submission) checks might flag.

In many cases the screen and report (submission) checks are the same check.  However, the screen checks do not prevent a user from saving the data when a result is returned as long as the result is not a Fatal result.  So, data with Critical 1 and lower results can be saved through the MP screens.  Although many report checks and screen checks are the exact same checks, check conditions for the report checks prevent many of them from running against "inactive" data.  The combination of the minimal import checks, ability to ignore screen checks, and the skipping of report (submission) checks for inactive data allows the submission of inactive MP data that would have otherwise been prevented by report (submission) checks in ECMPS 1.0.

## ECMPS 2.0 Issues

ECMPS 2.0 applies ECMPS 1.0 screen checks.  However, ECMPS 2.0 does not allow the saving of data with check results while ECMPS 1.0 only prevents the saving of data for Fatal results.  Additionally unlike ECMPS 1.0, ECMPS 2.0 applies screen checks as import checks and, again, does so without allowing the saving of the data when a check result is triggered.  **ECMPS 2.0 should allow the import and screen entry of the inactive MP data that ECMPS 1.0 would allow.**

## ECMPS 1.0 Inactive MP Record Definition

The original description indicated that Inactive data meant records that have a null End Date.  ECMPS 1.0 used the following rule for most MP data.

> The **Record Begin Date / End Date** and the **Evaluation Begin Date / End Date** do not overlap.
> Basically, **Record Begin Date** is after **Evaluation End Date** or **Record End Date** is before **Evaluation Begin Date**.
> A null **Record End Date** is always after the **Evaluation Begin Date**.
> **Evaluation Begin Date** is always 1/1/2008.
> **Evaluation End Date** is the Current Date plus a year.

> This definition applies to **Analyzer Range**, **Default**, **Formula**, **Load**, **Location**, **Method**, **Qualification**, **Rectangular Duct WAF**, **Span**, **System**, **System Component**, **System Fuel Flow**, **Unit Capacity**, and **Unit Fuel** data.

> The definition also applies to **Unit Control** data except that it's **Install Date** and **Retire Date** instead of Begin Date and End Date respectively.

> For **Component** data the definition is related to the definition above, but a **Component** is inactive when no related **System Component Begin Date / End Date** overlaps with **Evaluation Begin Date / End Date**.

**This ECMPS 1.0 definition of "inactive" for this purpose does not match the original definition for this ticket.**

**Comment by djw4erg** [comment]
## Affected ECMPS 1.0 Checks

**ECMPS 1.0 Screen Checks that are also Report (Submission) Checks that only run for "active" data.**

Active indicates that the data was active at some point during the **MP Evaluation Begin and End Date Range**, which is from January 1, 2008 through a year after the current date.

These checks allowed the submission of data in ECMPS 1.0 but would/could cause problems as import checks in ECMPS 2.0.

### Analyzer Range Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| COMPON-16 | Analyzer Range Code Valid | A | B, C | A, B |  |
| COMPON-37 | Dual Range Indicator Consistent with Analyzer Range Code |  | A, B, C | A |  |

### Component Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| COMPON-8 | Component ID Valid | A | B | A, B |  |
| COMPON-10 | Component Serial Number Valid |  | A |  |  |
| COMPON-11 | Component Manufacturer Valid |  | A |  |  |
| COMPON-12 | Component Type Code Valid | A | B, C | A, B |  |
| COMPON-13 | Component Sample Acquisition Method Code Valid |  | A, B, C | B | A |
| COMPON-14 | Component Basis Code Valid |  | A, B, C, D | B | A, B, C, D |

### Default Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| DEFAULT-47 | Default Parameter Code Valid | A | B, C | A |  |
| DEFAULT-48 | Default Operating Condition Code Valid |  | A, B, C, D, E | A |  |
| DEFAULT-49 | Default Value Valid | A | B, C, D, E, F, G | A |  |
| DEFAULT-50 | Default Units of Measure Code Valid | A, B | C | A |  |
| DEFAULT-51 | Default Purpose Code Valid  |  | A, B, C | A |  |
| DEFAULT-52 | Default Source Code Valid |  | A, B, C | A |  |
| DEFAULT-53 | Default Fuel Code Valid |  | A, B, C | A, B |  |
| DEFAULT-98 | Default Group ID Valid |  | A, B |  |  |

- **DEFAULT-47-B** is apparently implemented in **MonitorDefaultBaseDTO** but that check should be the equivalent of the **MP XSD**'s **DefaultParameterCodeType**, and the **MonitorDefaultBaseDTO** check should be updated by #6403.

### Formula Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| FORMULA-7 | Formula ID Valid | A | B | A, B |  |
| FORMULA-8 | Formula Parameter Code Valid | A | B, C | A, B |  |
| FORMULA-9 | Formula Code Valid | B | A, C, D | A, B |  |

### Load Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| LOAD-8 | Maximum Load Value Valid |  | A, B, C |  |  |
| LOAD-13 | Maximum Load Units of Measure Valid |  | A, B, C |  |  |

### Location Attribute Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| MONLOC-5 | Stack Ground Elevation Valid |  | A, B |  |  |
| MONLOC-6 | Stack Cross Area Flow Valid |  | A, B, C |  |  |
| MONLOC-7 | Stack Cross Area Exit Valid |  | A, B, C |  |  |
| MONLOC-8 | Stack Height Valid |  | A, B |  |  |
| MONLOC-9 | Stack Shape Code Valid |  | A, B |  |  |
| MONLOC-10 | Stack Material Code Valid |  | A, B |  |  |
| MONLOC-74 | Stack Bypass Indicator Valid |  | A |  |  |

### Method Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| METHOD-7 | Method Parameter Code Valid | A | B, C |  |  |
| METHOD-8 | Method Method Code Valid | A, B | C, D, E |  |  |
| METHOD-9 | Method Substitute Data Code Valid |  | A, B, C |  |  |
| METHOD-10 | Method Bypass Approach Code Valid |  | A, B |  |  |

### Qualification Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| QUAL-16 | Monitoring Qualification Qualification Type Code Valid | A | B, C, D, E |  |  |

### Qualification LME Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| QUAL-22 | Monitoring Qualification LME Data Qualification Year Valid | A | B |  |  |
| QUAL-25 | Monitoring Qualification LME Data Operating Hours Valid |  | A, B |  |  |

### Qualification Percent Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| QUAL-7 | Monitoring Qualification Percent Qualification Year Valid | A | B |  |  |
| QUAL-8 | Monitoring Qualification Percent Average Percent Value Valid |  | A, B, C |  |  |
| QUAL-27 | Monitoring Qualification Percent Year 1 Data Type Code Valid |  | A, B, C, D, E |  |  |
| QUAL-28 | Monitoring Qualification Percent Year 1 Data Year Valid |  | A, B |  |  |
| QUAL-29 | Monitoring Qualification Percent Year 1 Percentage Value Valid |  | A, B |  |  |
| QUAL-40 | Monitoring Qualification Percent Year 2 Data Type Code Valid |  | A, B, C, D |  |  |
| QUAL-41 | Monitoring Qualification Percent Year 2 Percentage Value Valid |  | A, B |  |  |
| QUAL-42 | Monitoring Qualification Percent Year 2 Data Year Valid |  | A, B |  |  |
| QUAL-43 | Monitoring Qualification Percent Year 3 Data Type Code Valid |  | A, B, C, D |  |  |
| QUAL-44 | Monitoring Qualification Percent Year 3 Percentage Value Valid |  | A, B |  |  |
| QUAL-45 | Monitoring Qualification Percent Year 3 Data Year Valid |  | A, B |  |  |

### Rectangular Duct WAF Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| DEFAULT-78 | Rectangular Duct WAF Duct Width at Test Location Valid |  | A, B | A |  |
| DEFAULT-79 | Rectangular Duct WAF Duct Depth at Test Location Valid |  | A, B | A |  |
| DEFAULT-80 | Rectangular Duct WAF Value Valid | A | B, C, D | A, D |  |
| DEFAULT-81 | Rectangular Duct WAF Method of Determination Valid |  | A, B |  |  |
| DEFAULT-86 | Rectangular Duct WAF Determination Date Valid |  | A, B, C |  |  |
| DEFAULT-87 | Rectangular Duct WAF Number of WAF Test Runs Valid |  | A, B, C |  |  |
| DEFAULT-88 | Rectangular Duct WAF Number of Method 1 Traverse Points in WAF Test Valid |  | A, B |  |  |
| DEFAULT-89 | Rectangular Duct WAF Number of Test Ports in WAF Test Valid |  | A, B, C |  |  |
| DEFAULT-90 | Rectangular Duct WAF Number of Method 1 Traverse Points in Reference Flow RATA Test Valid |  | A, B, C |  |  |

### Span (Flow) Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| SPAN-3 | Span MPF Value Valid |  | A, B, C | A, B |  |
| SPAN-6 | Span Value Valid |  | A, B, C, D, E, F, G |  |  |
| SPAN-7 | Span Full Scale Range Value Valid |  | A, B |  |  |
| SPAN-16 | Flow Span Value Valid |  | A, B, C, D |  |  |
| SPAN-17 | Flow Span Full Scale Range Value Valid |  | A, B, C |  | A, B, C |
| SPAN-20 | Span Component Type Code Valid | A | B | A, B |  |
| SPAN-21 | Span Units of Measure Code Valid | B | A, C | A |  |
| SPAN-50 | Span Method Code Valid |  | A, B, C |  |  |

### Span (non-Flow) Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| SPAN-6 | Span Value Valid |  | A, B, C, D, E, F, G |  |  |
| SPAN-7 | Span Full Scale Range Value Valid |  | A, B |  |  |
| SPAN-18 | Span Scale Code Valid  |  | A, B, C, D |  |  |
| SPAN-20 | Span Component Type Code Valid | A | B | A, B |  |
| SPAN-21 | Span Units of Measure Code Valid | B | A, C | A |  |
| SPAN-36 | Span Default High Range Value Valid |  | A, B, C, D |  |  |
| SPAN-37 | Default High Range Value Consistent with Span Value and Full Scale Range |  | A |  |  |
| SPAN-50 | Span Method Code Valid |  | A, B, C |  |  |
| SPAN-60 | Span MPC MEC Value Consistency Check  |  | A |  |  |

### System Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| SYSTEM-7 | Monitoring System ID Valid | A | B | A, B |  |
| SYSTEM-8 | System Type Code Valid | A | B, C, D | A, B |  |
| SYSTEM-9 | System Designation Code Valid  |  | A, B, C |  |  |
| SYSTEM-10 | System Fuel Code Valid |  | A, B, C |  |  |

### System Fuel Flow Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| FUELFLW-2 | Fuel Flow Maximum Fuel Flow Rate Valid | A | B | A, B |  |
| FUELFLW-8 | Fuel Flow Maximum Fuel Flow Rate Source Code Valid |  | A, B | A, B |  |
| FUELFLW-10 | Fuel Flow Units of Measure Code Valid | A, B | C | A |  |

### Unit Capacity Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| CAPAC-3 | Unit Capacity Maximum Heat Input Capacity Valid | A | B, C |  |  |

### Unit Control Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| CONTROL-1 | Control Parameter Code Valid | A | B | A, B |  |
| CONTROL-2 | Control Code Valid | A, B | C | A |  |
| CONTROL-4 | Control Optimization Date Valid |  | A | A |  |

### Unit Fuel Affected Checks
| Check Code | Check Name | Fatal | Non-Fatal | DTO | CS |
| :--- | :--- | :--- | :--- | :--: | :--: |
| FUEL-40 | Unit Fuel Demonstration GCV Valid |  | A, B |  |  |
| FUEL-41 | Unit Fuel Demonstration SO2 Valid |  | A, B |  |  |
| FUEL-45 | Unit Fuel Code Valid | A | B |  |  |
| FUEL-49 | Unit Fuel Ozone Season Indicator Valid |  | A |  |  |
| FUEL-51 | Unit Fuel Primary/Secondary Indicator Code Valid |  | A, B |  |  |

**Comment by esaber76** [comment]
## Issues Found During Performance Testing

Additional issues were found during performance testing. Per 9/12/2024 performance testing meeting, documenting these issues here as part of this ticket research.

**Example 1:** The following types of import and evaluation errors are generated for ORIS 1913, 1 & 2.

**Import:**

![image](https://github.com/user-attachments/assets/d272314d-e3d1-4047-819c-56dc41c5bc2f)

**Evaluate:** These are related to inactive SORX default records (1/1/2009 - 12/31/2009). 

![image](https://github.com/user-attachments/assets/5d3feefb-8ce9-4654-a643-d086014a338c)

**Example 2:** The following types of import and evaluation errors are generated for ORIS 4014, 2, 3 and 4.

**Import:**

![image](https://github.com/user-attachments/assets/9b9a8357-7341-479f-b4c0-a14824a3c13c)

**Evaluate:** These are related to inactive SORX default records (1/1/2009 - 12/31/2017).

![image](https://github.com/user-attachments/assets/61857b7f-6305-4313-9de6-59fbd6d2e8d1)

**Comment by djw4erg** [comment]
## Reply to [Issues Found During Performance Testing](https://github.com/US-EPA-CAMD/easey-ui/issues/5942#issuecomment-2346977097)

This issue is not really an "**inactive record**" issue in my opinion.  The failing **DTO** check seems to implement **DEFAULT-47-B**, but it should implement the **Default Parameter Code Type** from the **ECMPS 1.0 MP XSD**.  That type definition includes "**SORX**" (Maximum SO2 Emission Rate).  The definition includes all the default parameter codes allowed by the ECMPS 2.0 check except for "**BWA**" (Moisture Fraction in Ambient Air).  Changing the **DTO** check to match the **XSD Default Parameter Code Type** will eliminate the problem for "**SORX**".

Note that the "**SORX**" appears to be a **pre-ECMPS** relic with all **23** instances starting on **1/1/2009**.

Additionally we probably need to check with Charlie to determine whether reporting "BWA" (Moisture Fraction in Ambient Air) for Monitor Defaults is actually allowed.

**Comment by djw4erg** [comment]
## Target Check Results

| Result Code | Result Description| Type | Rows |
| :--- | :--- | :--: | ---: |
| COMPON-8-B | **Component ID** does not consist of 3 alphanumeric characters. | DTO | 0 |
| COMPON-12-B | **Component Type Code** is not in the list of valid values. | DTO | 0 |
| **COMPON-13-A** | Component **Sample Acquisition Method Code** is not in the list of valid values. | **CS** | **19** |
| COMPON-13-B | Component **Sample Acquisition Method Code** not reported. | DTO | 0 |
| **COMPON-14-A** | Component **Basis Code** not reported. | **CS** | **1** |
| COMPON-14-B | Component **Basis Code** is not valid for component type. | DTO, CS | 0 |
| COMPON-14-C | Component **Basis Code** not the same as submitted value. | CS | 0 |
| COMPON-14-D | Component **Basis Code** was unexpectedly reported. | CS | 0 |
| COMPON-16-B | **Analyzer Range Code** is not in the list of valid values. | DTO | 0 |
| COMPON-37-A | Analyzer Range **Dual Range Indicator** not reported. | DTO | 0 |
| CONTROL-1-B | Control **Parameter Code** is not in the list of valid values. | DTO | 0 |
| CONTROL-4-A | Control **Optimization Date** is not between the **Installation Date** and the **Retire Date**. | DTO | 0 |
| DEFAULT-48-A | Default **Operating Condition Code** not reported. | DTO | 0 |
| **DEFAULT-51-A** | Default **Purpose Code** not reported. | DTO | **2** |
| **DEFAULT-52-A** | Default **Source Code** not reported. | **DTO** | **554** |
| **DEFAULT-53-A** | Default **Fuel Code** not reported. | **DTO** | **101** |
| DEFAULT-53-B | Default **Fuel Code** is not in the list of valid values. | DTO | 0 |
| DEFAULT-78-A | **Rectangular Duct WAF Duct Width** not reported. | DTO | 0 |
| DEFAULT-79-A | **Rectangular Duct WAF Duct Depth** not reported. | DTO | 0 |
| DEFAULT-80-D | **Rectangular Duct WAF Value** not between 0 and 1, excluding endpoints. | DTO | 0 |
| FORMULA-7-B | **Formula ID** does not consist of 3 alphanumeric characters. | DTO | 0 |
| FORMULA-8-B | Formula **Parameter Code** is not in the list of valid values. | DTO | 0 |
| FORMULA-9-A | **Formula Code** (or **Text**) was not reported. | DTO | 0 |
| FUELFLW-2-B | Fuel Flow **Maximum Fuel Flow Rate** is not greater than 0 (zero). | DTO | 0 |
| FUELFLW-8-A |Fuel Flow **Maximum Fuel Flow Rate Source Code** not reported. | DTO | 0 |
| FUELFLW-8-B |Fuel Flow **Maximum Fuel Flow Rate Source Code** is not in the list of valid values. | DTO | 0 |
| SPAN-3-A | For Flow Span, **MPF Value** not reported. | DTO | 0 |
| **SPAN-3-B** | For Flow Span, **MPF Value** is less that 500,000. | **DTO** | **8** |
| **SPAN-17-A** | For Flow Span, **Flow Full Scale Range** not reported. | **CS** | **70** |
| **SPAN-17-B** | For Flow Span, **Flow Full Scale Range** is less than the Flow **Span Value**. | **CS** | **9** |
| **SPAN-17-C** | For non-Flow Span, **Flow Full Scale Range** is not null. | **CS** | **1** |
| SPAN-20-B | Span **Component Type Code**  is not a valid **span** component type. | DTO | 0 |
| SPAN-21-A | Span **Units of Measure Code** not reported. | DTO | 0  |
| **SYSTEM-7-B** | **Monitoring System ID** does not consist of 3 alphanumeric characters. | **DTO** | **1** |
| SYSTEM-8-B | **System Type Code** is not in the list of valid values. | DTO | 0  |

## TODOs:

1. Determine whether COMPON-13 and COMPON-14 Check Service checks should be included.
   - **Yes**
2. Determine whether only the Rows greater than 0 rows should be included in the development ticket.
   - **Yes**
3. Generate ticket that includes rows from the following table, either all or just Row Exists equal "Yes".
   - Determine whether specific validation instead of all validation can be turned off for a DTO check.
     - Should explore using [DTO Custom validation classes](https://www.npmjs.com/package/class-validator#custom-validation-classes).
   - Handled in #6404

**Comment by djw4erg** [comment]
## Row Count Script

```
-- COMPON-8-B
select  *
  from  COMPONENT dat
 where  length( trim( dat.Component_Identifier ) ) != 3;

-- COMPON-12-B
select  *
  from  COMPONENT dat
 where  not exists
        (
            select  1
              from  COMPONENT_TYPE_CODE cod
             where  cod.Component_Type_Cd = dat.Component_Type_Cd
        );

-- COMPON-13-A
select  *
  from  COMPONENT dat
 where  dat.Acq_Cd is null
    and dat.Component_Type_Cd not in ( 'CALR', 'DAHS', 'DL', 'DP', 'FLC', 'GCH', 'MS', 'PLC', 'PRB', 'PRES', 'TANK', 'TEMP' );

-- COMPON-13-B
select  *
  from  COMPONENT dat
 where  not exists
        (
            select  1
              from  ACQUISITION_METHOD_CODE cod
             where  cod.Acq_Cd = dat.Acq_Cd
        )
   and  dat.Acq_Cd is not null;

-- COMPON-14-A
select  *
  from  COMPONENT dat
 where  dat.Basis_Cd is null
    and dat.Component_Type_Cd in ( 'CO2', 'FLOW', 'HCL', 'HF', 'HG', 'NOX', 'O2', 'SO2', 'STRAIN' );

-- COMPON-14-B
select  *
  from  COMPONENT dat
 where  (
            dat.Component_Type_Cd in ( 'CO2', 'HCL', 'HF', 'HG', 'NOX', 'SO2' ) and dat.Basis_Cd not in ( 'D', 'W' )
            or
            dat.Component_Type_Cd = 'FLOW' and dat.Basis_Cd != 'W'
            or
            dat.Component_Type_Cd = 'O2' and coalesce( dat.Basis_Cd, 'N' ) not in ( 'B', 'D', 'W' )
            or
            dat.Component_Type_Cd = 'PM' and coalesce( dat.Basis_Cd, 'N' ) not in ( 'D', 'N', 'W' )
            or
            dat.Component_Type_Cd = 'STRAIN' and dat.Basis_Cd != 'D'
        )
   and  dat.Basis_Cd is not null;

-- COMPON-14-C
select  *
  from  COMPONENT cmp
        join USED_IDENTIFIER usd
          on usd.Idkey = cmp.Component_Id
         and usd.Table_Cd = 'C'
         and usd.Formula_Or_Basis_Cd is not null
 where  cmp.Component_Type_Cd in ( 'CO2', 'FLOW', 'HCL', 'HF', 'HG', 'NOX', 'O2', 'PM', 'SO2', 'STRAIN' )
   and  cmp.Basis_Cd is not null
   and  coalesce( cmp.Basis_Cd, 'N' ) != 'B'
   and  coalesce( cmp.Basis_Cd, 'N' ) != coalesce( usd.Formula_Or_Basis_Cd, 'N' );

-- COMPON-14-D
select  *
  from  COMPONENT dat
 where  dat.Basis_Cd is not null
    and dat.Component_Type_Cd not in ( 'CO2', 'FLOW', 'HCL', 'HF', 'HG', 'NOX', 'O2', 'PM', 'SO2', 'STRAIN' );

-- COMPON-16-B
select  *
  from  ANALYZER_RANGE dat
 where  not exists
        (
            select  1
              from  ANALYZER_RANGE_CODE cod
             where  cod.Analyzer_Range_Cd = dat.Analyzer_Range_Cd
        );

-- COMPON-37-A
select  *
  from  ANALYZER_RANGE dat
 where  dat.Dual_Range_Ind is null;

-- CONTROL-1-B
select  *
  from  UNIT_CONTROL dat
 where  not exists
        (
            select  1
              from  CONTROL_EQUIP_PARAM_CODE cod
             where  cod.Control_Equip_Param_Cd = dat.Ce_Param
        );

-- CONTROL-4-A
select  *
  from  UNIT_CONTROL dat
 where  dat.Opt_Date is not null
   and  (
            dat.Opt_Date < dat.Install_Date
            or
            dat.Retire_Date is not null and
            dat.Opt_Date > dat.Retire_Date
        );

-- DEFAULT-48-A
select  *
  from  MONITOR_DEFAULT dat
 where  dat.Operating_Condition_Cd is null;

-- DEFAULT-51-A
select  *
  from  MONITOR_DEFAULT dat
 where  dat.Default_Purpose_Cd is null;

-- DEFAULT-52-A
select  *
  from  MONITOR_DEFAULT dat
 where  dat.Default_Source_Cd is null;

-- DEFAULT-53-A
select  *
  from  MONITOR_DEFAULT dat
 where  dat.Fuel_Cd is null;

-- DEFAULT-53-B
select  *
  from  MONITOR_DEFAULT dat
 where  not exists
        (
            select  1
              from  FUEL_CODE cod
             where  cod.Fuel_Cd = dat.Fuel_Cd
        )
   and  dat.Fuel_Cd is not null;

-- DEFAULT-78-A
select  *
  from  RECT_DUCT_WAF dat
 where  dat.Duct_Width is null;

-- DEFAULT-79-A
select  *
  from  RECT_DUCT_WAF dat
 where  dat.Duct_Depth is null;

-- DEFAULT-80-D
select  *
  from  RECT_DUCT_WAF dat
 where  (
            dat.Waf_Value <= 0
            or
            dat.Waf_Value >= 1
        );

-- FORMULA-7-B
select  *
  from  MONITOR_FORMULA dat
 where  length( trim( dat.Formula_Identifier ) ) != 3;

-- FORMULA-8-B
select  *
  from  MONITOR_FORMULA dat
 where  dat.Parameter_Cd not in ( 'CO2', 'CO2C', 'CO2M', 'FC', 'FD', 'FGAS', 'FLOW', 'FOIL', 'FW', 'H2O', 'HCLRE', 'HCLRH', 'HFRE', 'HFRH', 'HGRE', 'HGRH', 'HI', 'HIT', 'NOX', 
                                  'NOXR', 'OILM', 'PM', 'PMRE', 'PMRH', 'SO2', 'SO2R', 'SO2RE', 'SO2RH' );

-- FORMULA-8-B
select  *
  from  MONITOR_FORMULA dat
 where  dat.Equation_Cd is null
   and  dat.Formula_Equation is null;

-- FUELFLW-2-B
select  *
  from  SYSTEM_FUEL_FLOW dat
 where  dat.Max_Rate <= 0;

-- FUELFLW-8-A
select  *
  from  SYSTEM_FUEL_FLOW dat
 where  dat.Max_Rate_Source_Cd is null;

-- FUELFLW-8-B
select  *
  from  SYSTEM_FUEL_FLOW dat
 where  not exists
        (
            select  1
              from  MAX_RATE_SOURCE_CODE cod
             where  cod.Max_Rate_Source_Cd = dat.Max_Rate_Source_Cd
        );

-- SPAN-3-A
select  *
  from  MONITOR_SPAN dat
 where  dat.Mpf_Value is null
   and  dat.Component_Type_Cd = 'FLOW';

-- SPAN-3-B
select  *
  from  MONITOR_SPAN dat
 where  dat.Mpf_Value < 500000
   and  dat.Component_Type_Cd = 'FLOW';

-- SPAN-17-A
select  *
  from  MONITOR_SPAN dat
 where  dat.Flow_Full_Scale_Range is null
   and  dat.Component_Type_Cd = 'FLOW';

-- SPAN-17-B
select  *
  from  MONITOR_SPAN dat
 where  dat.Flow_Full_Scale_Range < dat.Span_Value
   and  dat.Component_Type_Cd = 'FLOW';

-- SPAN-17-C
select  *
  from  MONITOR_SPAN dat
 where  dat.Flow_Full_Scale_Range is not null
   and  dat.Component_Type_Cd != 'FLOW';

-- SPAN-20-B
select  *
  from  MONITOR_SPAN dat
 where  not exists
        (
            select  1
              from  COMPONENT_TYPE_CODE cod
             where  cod.Component_Type_Cd = dat.Component_Type_Cd
               and  coalesce( cod.Span_Indicator, 0 ) = 1
        );

-- SPAN-21-A
select  *
  from  MONITOR_SPAN dat
 where  dat.Span_Uom_Cd is null;

-- SYSTEM-7-B
select  *
  from  MONITOR_SYSTEM dat
 where  length( trim( dat.System_Identifier ) ) != 3;

-- SYSTEM-8-B
select  *
  from  MONITOR_SYSTEM dat
 where  not exists
        (
            select  1
              from  SYSTEM_TYPE_CODE cod
             where  cod.Sys_Type_Cd = dat.Sys_Type_Cd
        );
```
