### ISSUE TITLE
GITHUB Enterprise Migration Project

### ISSUE THREAD

**Issue by spetros-do** [US-EPA-CAMD/PI-1#6098]
Migration project from Github.com to GitHub Enterprise.

**Objectives:**
- to ensure migration meets diverse needs and enhance workflows
- seamless transition with minimal disruption to workflows & tool dependencies
- complete migration of settings for CI/CD Pipelines - i.e. GitHub Actins, including branch protection rules, access controls & etc.
- complete migration of all required active repositories (data), including code, branches, tags & commit history.  

**Implementation Steps:**

1. Migrate EPA's Github.com Devops and AuthAPI  repos to Github Enterprise Cloud.

2. Test/confirm the migration, including, but not limited to (more to be identified and cataloged during test migration):

- [ ]  Confirm workflows and features match (e.g., actions)
- [ ]  Test pull requests
- [ ]  Side-by-side comparison of github.com repo to enterprise repo
- [ ]  Confirm repo dependencies

 
Tentative planned completion date: 3/1/24

3. Migrate additional repos (or entire organization)

4. Refactor actions (if/as needed)

**Resources:**
https://docs.github.com/en/migrations/using-github-enterprise-importer/migrating-between-github-products/overview-of-a-migration-between-github-products#running-your-migrations

**Comment by spetros-do** [comment]
Org Level Migration imitated on 3/6/2024.
Currently updating/supporting intermittent login errors due to possible Token issues.
Shold be able close this ticket once EPA / Mike Heese confirms status.

**Comment by spetros-do** [comment]
Migration successfully completed.

**Comment by mark-hayward-erg** [comment]
Reopening this to investigate why tickets are automatically being transitioned to Done.

Possible causes 
* when pull requests are merged (check all repos with a develop branch)
* when tickets are updated to "closed"
