### ISSUE TITLE
"Feature" or "Epic" Ticket with lists of child tickets

### ISSUE THREAD

**Issue by MaryFoleyGDIT** [US-EPA-CAMD/PI-1#6130]
```[tasklist]
### Tasks
- [ ] https://github.com/US-EPA-CAMD/easey-ui/issues/6136
- [ ] https://github.com/US-EPA-CAMD/easey-ui/issues/6137
- [ ] https://github.com/US-EPA-CAMD/easey-ui/issues/6138
```
