### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by david-cvp** [US-EPA-CAMD/PI-1#635]
Identify common functions to be moved into shared library repositories

Header/footer, 508 updates, and more

- [ ] Database entities need to be moved to easey-db-entities repo
- [ ] DTOs need to be moved to easey-dtos repo
- [ ] Common utilities and unit test mock functions moved to easey-shared
- [ ] Set up NPM packages and re-install in the original repos

No dependencies, just making this change to support code maintenance by consolidating shared functions

**This task will require additional support from scrum team developers to assist Jason**

5/6 update: Jason will identify & divide this work for Emissioners + Datateers
Tickets created in Emissioners/Datateers backlog to make the changes
