### ISSUE TITLE
 Implement Bulk Data Files Solution for CAMPD Release Data Types 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#662]
Original estimate: 100 (1/27/22) 

Targeted release date for bulk data files:  June 2022

## EPIC Benefit

As apart of the this epic the EPA wants to provide users the ability to access the bulk data files through a UI and programmatically through a script.   

- [ ] Repackaging/ Scheduling jobs for bulk data files: 

- [ ] Copy over files from FTP site 

- [ ] Provide UI for bulk data files 

- [ ] Quartz/ CDX work : Quartz requires authentication which will require the CDX integration.

### Files To Be Generated Requirements:  

 

1. **Facility/Unit Attributes Files** 

 **Data groupings:**  
Provide a file for each year that contains all facilities up until the current year. Valid years: 1980, 1985, 1990, 1995 – up until the current year 

**Valid Years:**  
Valid years: 1980, 1985, 1990, 1995 – up until the current year 

**File Format:** 
 CSV  

**Update Frequency:**  
When the next year of records is generated in UNIT_FACT (OP_YEAR)  
Facility/ unit attribute files should update with any refresh to UNIT_FACT table 

**Example File Name:** 
Facility-2019.csv 

 
**# of Files Total:** 
31 files in total through 2022 

**Facility/ unit attributes Data Elements:**  
The facility/ unit attributes files will return the following data elements:  
The records will be ordered by Facility ID> Unit ID > Year and adhere to the csv labels in the Master Data Dictionary  

STATE 
FACILITY_NAME 
ORISPL_CODE 
UNITID 
ASSOC_STACKS 
OP_YEAR 
PRG_CODE_INFO 
EPA_REGION 
NERC_REGION 
COUNTY 
COUNTY_CODE 
FIPS_CODE 
SOURCE_CAT 
LATITUDE 
LONGITUDE 
OWN_DISPLAY / OPR_DISPLAY * 
SO2_PHASE 
NOX_PHASE 
UNIT_TYPE_INFO 
PRIMARY_FUEL_INFO 
SECONDARY_FUEL_INFO 
SO2_CONTROL_INFO 
NOX_CONTROL_INFO 
PART_CONTROL_INFO 
HG_CONTROL_INFO 
COMR_OP_DATE 
OP_STATUS_INFO 
CAPACITY_INPUT (mmBtu/hr) 
associatedGeneratorsAndNameplateCapacity 

*REPORT_FREQ in PROGRAM_YEAR_DIM 
*GENID (Generator ID) in generator table 
OWN_DISPLAY / OPR_DISPLAY in OWNER_DISPLAY_FACT table 

 

**2. Apportioned Hourly Emissions Files:**  

**Data Groupings:**  
Provide hourly emissions files by year and quarter up until the last reported quarter. Valid years: 1995 – last reported quarter   
Provide hourly emissions files by state and year up until the last reported year. Valid years: 1995 – last reported year   

- **Provide Hourly emissions files by year and quarter:**  

**Valid Years:**  
1995 – last reported quarter   

**File Format:**  
CSV

**Update Frequency:**  
Quarterly grouping: At the end of each quarterly reporting period, with nightly check for changes/updates   

**Example File Name:** 
Emissions-Hourly-1995-Q1.csv 
Emissions-Hourly-1995-Q2.csv 
Emissions-Hourly-1995-Q3.csv 
Emissions-Hourly-1995-Q4.csv 

**# of Files Total:** 
 108 files in total through 2021  

**Data Elements:**  
The hourly emission files by year and quarter will return the following data elements  The records will be ordered by  facilityId, unitId, date, and hour  and adhere to the csv data labels in the Master Data Dictionary.  

stateCode  

facilityName   

facilityId  

unitId   

unitType   

associatedStacks   

primaryFuelInfo  

 secondaryFuelInfo   

so2ControlInfo  

 pmControlInfo   

noxControlInfo  

 HgControlInfo 

  programCodeInfo   

grossLoad   

steamLoad   

so2Mass   

so2Rate   

noxMass   

noxRate   

co2Mass   

co2Rate   

heatInput  

 so2MassMeasureFlg   

so2RateMeasureFlg  

 noxMassMeasureFlg   

noxRateMeasureFlg   

co2MassMeasureFlg    

co2RateMeasureFlg   

date    

hour  

 opTime 

 

- **Provide hourly emissions files by state and year**  

**Valid Years:**   

1995 – last reported year   

**File Format:**   

CSV 

 **Update Frequency:**  
Annual grouping: At the end of the 4th quarter reporting period each year, with nightly check for changes/updates 

**Example File Name**:
Emissions-Hourly-2020-PA. csv 
Emissions-Hourly-2020-MD.csv  

**# of files in total:** 
 1350 files in total through 2021   
 

 **Data Elements:**  
The hourly emission files by state and year will return the following data elements  The records will be ordered by  facilityId, unitId, date, and hour  and adhere to the csv data labels in the Master Data Dictionary.  

stateCode  

facilityName   

facilityId  

unitId   

unitType   

associatedStacks   

primaryFuelInfo  

 secondaryFuelInfo   

so2ControlInfo  

 pmControlInfo   

noxControlInfo  

 HgControlInfo 

  programCodeInfo   

grossLoad   

steamLoad   

so2Mass   

so2Rate   

noxMass   

noxRate   

co2Mass   

co2Rate   

heatInput  

 so2MassMeasureFlg   

so2RateMeasureFlg  

 noxMassMeasureFlg   

noxRateMeasureFlg   

co2MassMeasureFlg    

co2RateMeasureFlg   

date    

hour  

 opTime 

 

 

**3. Apportioned Daily Emissions:**  

**Data Groupings:**  
Provide daily emissions files by year and quarter up until the last reported quarter Valid years: 1995 - last reported quarter   
Provide daily emissions files by year and state up until the last reported year. Valid years: 1995 - last reported year   

 

- **Provide Daily Emissions files by year and quarter**  

**Valid Years**  
1995 - last reported quarter 

**File Format:** 
CSV  

**Update Frequency**  
Quarterly grouping: At the end of each quarterly reporting period, with nightly check for changes/updates 

 
**Example File Name:**   

Emissions-Daily-2020-Q1.csv 

Emissions-Daily-2020-Q2.csv 

Emissions-Daily-2020-Q3.csv 

Emissions-Daily-2020-Q4.csv  

 
**# of files in total:** 
 108  files in total through 2021

**Data Elements:**  
The records will be ordered by Facility > Unit > Date and adhere to the csv data labels in the Master Data Dictionary :  
 
STATE 
FACILITY_NAME 
ORISPL_CODE 
UNITID 
ASSOC_STACKS 
OP_DATE 
SUM_OP_TIME 
COUNT_OP_TIME 
GLOAD 
SLOAD 
SO2_MASS 
SO2_RATE 
NOX_MASS 
NOX_RATE 
CO2_MASS 
CO2_RATE 
HEAT_INPUT 
PRIMARY_FUEL_INFO 
SECONDARY_FUEL_INFO 
UNIT_TYPE_INFO 
SO2_CONTROL_INFO 
PART_CONTROL_INFO 
NOX_CONTROL_INFO 
HG_CONTROL_INFO 
PRG_CODE_INFO 

 

- **Provide Daily Emissions files by year and state**
  
**Valid Years**  
1995 - last reported year  

**File Format:** 
CSV  

**Update Frequency**  
 At the end of the 4th quarter reporting period each year, with nightly check for changes/updates 

**Example File Name:** 
Emissions-Daily-2020-PA.csv  
Emissions-Daily-2020-TX.csv  

 **# of files in total:** 
1350 files in total through 2021  
 

**Data Elements:**  
The records will be ordered by Facility > Unit > Date and adhere to the csv data labels in the Master Data Dictionary :   
STATE 
FACILITY_NAME 
ORISPL_CODE 
UNITID 
ASSOC_STACKS 
OP_DATE 
SUM_OP_TIME 
COUNT_OP_TIME 
GLOAD 
SLOAD 
SO2_MASS 
SO2_RATE 
NOX_MASS 
NOX_RATE 
CO2_MASS 
CO2_RATE 
HEAT_INPUT 
PRIMARY_FUEL_INFO 
SECONDARY_FUEL_INFO 
UNIT_TYPE_INFO 
SO2_CONTROL_INFO 
PART_CONTROL_INFO 
NOX_CONTROL_INFO 
HG_CONTROL_INFO 
PRG_CODE_INFO 

 
**4. MATS emissions:**
Note: Some MATS sources were given compliance extensions and therefore may not have reported emissions for several years meaning that not all states may have completed data from 2015 

 
**Data Groupings:**  
Provide MATs files by year and quarter until the last reported quarter. Valid years: 2015- last reported quarter  
Provide MATs files by state  and year  until the last reported year . Valid years: 2015- last reported year  

- **Provide MATS Data by year and quarter**

**Valid Years:**  
2015- last reported quarter  

**File Type:**  
Csv 

**Update Frequency:**  
Quarterly grouping: At the end of each quarterly reporting period, with nightly check for changes/updates   

**Example File Name:** 
MATS-Hourly-2020-Q1.csv 
MATS-Hourly-2020-Q2.csv 
MATS-Hourly-2020-Q3.csv 
MATS-Hourly-2020-Q4.csv  

 
**# of files in total:**
note: mats data is incomplete so there isn’t an estimate on how many files will be generated

**Data Elements:**  
The system will return the following data elements ordered by: facilityId > unitId > date > hour. The data eleemnts will adhere to the csv data labels in the Master data dictionary 

stateCode 
facilityName 
facilityId 
unitId 
date 
hour 
opTime 
matsGrossLoad 
matsHeatInput 
hgOutputRate 
hgInputRate 
hgMass 
hgMassMeasureFlg 
hclOutputRate 
hclInputRate 
hclMass 
hclMassMeasureFlg 
hfOutputRate 
hfInputRate 
hfMass 
hfMassMeasureFlg 
associatedStacks 
steamLoad 
primaryFuelInfo 
secondaryFuelInfo 
unitType 
so2ControlInfo 
noxControlInfo 
pmControlInfo 
hgControlInfo 

- **Provide MATS Data by state and year**  

Valid Years:  
2015- last reported year  

**File Type:**  
Csv 

 
**Update Frequency:**  
Annual grouping: At the end of the 4th quarter reporting period each year, with nightly check for changes/updates   

 
**Example File Name:**  :
MATS-Hourly-2020-PA.csv  
MATS-Hourly-2020-TX.csv 

 **# of files in total:** 
 (note: mats data is incomplete so there isn’t an estimate on how many files will be generated) 

**Data Elements:**  
The system will return the following data elements ordered by: facilityId > unitId > date > hour. The data eleemnts will adhere to the csv data labels in the Master data dictionary 

stateCode 

facilityName 

facilityId 

unitId 

date 

hour 

opTime 

matsGrossLoad 

matsHeatInput 

hgOutputRate 

hgInputRate 

hgMass 

hgMassMeasureFlg 

hclOutputRate 

hclInputRate 

hclMass 

hclMassMeasureFlg 

hfOutputRate 

hfInputRate 

hfMass 

hfMassMeasureFlg 

associatedStacks 

steamLoad 

primaryFuelInfo 

secondaryFuelInfo 

unitType 

so2ControlInfo 

noxControlInfo 

pmControlInfo 

hgControlInfo 

 

 
**6. Allowance Transactions:**  

**Data Groupings:**  
One file per program. retired/active allowance programs, values: ARP, CAIRNOX, CAIROS, CAIRSO2, CSNOX, CSNOXOS, CSOSG1/2, CSSO2G1/2, NBP, OTC, TXSO2 E.g., The ARP transaction file will have all the transactions for the ARP program 

**File Type:**  
CSV 

 
**Update Frequency:**  
- Annually for active programs at the end of the 4th calendar quarter  Transactions - updated annually January 30th
- check for updates/changes to retired programs – will need to further discuss with the development on how to tackle this

  
**Example File Name**: 
Transactions-ARP 
Transactions-CSNOX  

 
**# of files in total:** 
13 files in total (1 per program)  

**Data Elements:**  
The system returns the following data elements, and the elements are ordered by PRG_CODE> TRANSACTION_ID > VINTAGE_YEAR > START_BLOCK. The data labels will adhere to the csv labels in the master data dictionary  
PRG_CODE 
TRANSACTION_ID 
TRANSACTION_TOTAL 
TRANSACTION_TYPE 
SELL_ACCT_NUMBER 
SELL_ACCT_NAME 
SELL_ACCOUNT_TYPE 
SELL_FACILITY_NAME 
SELL_ORISPL_CODE 
SELL_STATE 
SELL_EPA_REGION 
SELL_SOURCE_CAT 
SELL_OWN_DISPLAY_NAME 
BUY_ACCT_NUMBER 
BUY_ACCT_NAME 
BUY_ACCOUNT_TYPE 
BUY_FACILITY_NAME 
BUY_ORISPL_CODE 
BUY_STATE 
BUY_EPA_REGION 
BUY_SOURCE_CAT 
BUY_OWN_DISPLAY_NAME 
TRANSACTION_DATE 
VINTAGE_YEAR 
START_BLOCK 
END_BLOCK 
TOTAL_BLOCK 

**7. Compliance (Allowance Based):**  

**Data Grouping:**  
One file per program. retired/active allowance programs, values: ARP, CAIRNOX, CAIROS, CAIRSO2, CSNOX, CSNOXOS, CSOSG1/2, CSSO2G1/2, NBP, OTC, TXSO2 . E.g., The ARP file will have all compliance records specific to the ARP program  

**File Type:**  
CSV 

**Update Frequency:**  
Annually, plus checking for updates/changes 
Compliance (both allowance & emissions) - updated annually June 30th

**Example File Name:** 
Compliance-ARP 
Compliance-CSNOX 

**# of files in total:** 
13 files in total one per program  

**Data Elements:**     
The system will return the following data elements for programs, ARP, CAIRNOX, CAIROS, CAIRSO2, CSNOX, CSNOXOS, CSOSG1/2, CSSO2G1/2, and TXSO2. The data elements will be ordered by PRG_CODE > OP_YEAR >ACCOUNT_NUMBER:  and adhere to the csv data labels in the master data dictionary.  
PRG_CODE 
OP_YEAR 
ACCOUNT_NUMBER 
ACCOUNT_NAME 
FACILITY_NAME 
ORISPL_CODE 
UNITS_AFFECTED 
ALLOCATED 
TOTAL_HELD 
COMP_YEAR_EMISS 
OTHER_DEDUCT 
TOTAL_DEDUCT 
CARRIED_OVER 
EXCESS_EMISS 
OWN_DISPLAY 
OPR_DISPLAY 
STATE 

The system will return the following data elements for programs, NBP and OTC. The data elements will be ordered by PRG_CODE > OP_YEAR >ACCOUNT_NUMBER :  and adhere to the csv data labels in the master data dictionary. 
PRG_CODE 
OP_YEAR 
ACCOUNT_NUMBER 
ACCOUNT_NAME 
FACILITY_NAME 
ORISPL_CODE 
UNITS_AFFECTED 
ALLOCATED 
BANKED_HELD 
CURRENT_HELD 
TOTAL_HELD 
COMP_YEAR_EMISS 
OTHER_DEDUCT 
TOTAL_REQ_DEDUCT 
CURRENT_DEDUCT 
DEDUCT_1_1 
DEDUCT_2_1 
TOTAL_DEDUCT 
CARRIED_OVER 
EXCESS_EMISS 
OWN_DISPLAY 
OPR_DISPLAY 
STATE 

**8. Compliance (Emission Based):** 

**Data Grouping**  
One file per program (one file for the ARP NOx Program only  )  

**File Type:**  
CSV 

**File Name Example**: 
Compliance-ARPNOX 

**# of files in total:**
1 file in total

**Update Frequency:**  
Annually, plus checking for updates/changes  - Will look into when the update should happen  
Compliance (both allowance & emissions) - updated annually June 30th

 
**Data Elements:**  
The system will return the following data elements for the ARP program programs. The recrods will be ordered by PRG_CODE > OP_YEAR > ORISPL_CODE > UNITID . The data labels should adhere to the csv data labels in the Master Data Dictionary.  

OP_YEAR 
FACILITY_NAME 
ORISPL_CODE 
UNITID 
OWN_DISPLAY 
OPR_DISPLAY 
STATE 
COMP_PLAN_TYPE_CD 
AVG_PLAN_ID 
EMISS_LIMIT_DISPLAY 
ACT_EMISS_RATE 
AVG_PLAN_ACT_EMISS_RATE 
IN_COMPLIANCE 

 

### Files to be copied over from the EPA FTP site:  

 

 

**1. Emissions, QA, Monitoring Plans XML Files**  

**Data Grouping:**  
Need to copy over emissions, QA, and monitoring plans XML files from the FTP site. 
There are three folders – emissions, qa, and monitoring plan 
folders are located here: https://gaftp.epa.gov/DMDnLoad/xml/

**File Type:** 
XML- Out of Scope: Will be copied over once ECMPS goes live and FTP site goes down . keep files zipped 
per backlog refinement on 3/9, files older than the last five years should be provided on the bulk data files UI on campd. 

**Update Frequency:**  
Will have to check nightly for updates/changes to these files. 

 

**File Name:** 
Will maintain the file names on the FTP site  

 

 

**2. EDRs** - Per backlog refinement on 3/9  will need to provide the EDRS on the CAMPD UI. keep the files zipped 

**Data Grouping:**  
Need to copy/move over EDRs 
See folder here: https://gaftp.epa.gov/DMDnLoad/ 

**File Type:**  
EDR 

**Update Frequency:**  
No updates/check 

**File Name:** 
Will maintain the file names on the FTP site 

 

**3. ARP Initial Allocations:**  : In scope: Will be provided on the UI as a single/ unzipped file 

**Data Grouping:**  
Single file that needs to be copied over from the FTP site. The file is arp_initial_allocations.zip on the FTP site under Allowances. 

**Update Frequency:**  
No Updates/ checks 
The file linked to above, needs to exist in the bulk data files of CAMPD as it currently exists in AMPDs FTP. 

**File Name:** 
Will maintain the file names on the FTP site 

## UI Requirements

**Data Type:**  

Values: Facility, Emissions, Mercury and Air Toxics Emissions (MATS), Allowance, Compliance- displayed in alphabetical order  

Optional  

Single Select  

Drop down 

Filter will display select by default  

 

 

**Sub Type:**  

Values: Given that a user has selected Emissions as a data type then the following sub type values are available: Hourly , Daily  

Optional  

Single select  

Drop down  

Sub type is only applicable to the emissions data type  

Filter will display select by default  

 

 

**Grouping:**  

 

Values: Given that a user has selected Hourly or Daily as a data sub type then the following groupings are available: Quarterly, State  

Values: Given that a user has selected Mercury and Air Toxics Emissions (MATS) as a data type then the following groupings are available: Quarterly, State 

Optional 

Single select  

Drop down 

Filter will display select by default   

 

 

 

**Search**  

Conduct a search on file name and file description  

Contains search  

Case insensitive  

User can search for multiple words: ex. Emissions 2020  PA  

If no filter criteria are applied, then the search will be conducted on all files  

Search is limited to the results in the dats grid  

 

 

If the user conducts a search and no files are found, then the system will display the following message:  

No results match that search criteria. Please change the criteria and try again. 

 

 

 

**Change Criteria** 

 
The user will have the ability to clear one, many, or all filter criteria 
If the user changes data type or sub data type, then: 

The filter criteria displayed updates accordingly 

No previously entered filter criteria is retained 

If a user changes data type or sub data type, then filter criteria is cleared 

 

 

If a user selects the Clear all functionality, then all the applied filter criteria is cleared  and the system will only display the data type filter by default 

 

 

 

 

**Data Table**  

 

The data table will contain the following columns: File name, Date updated, Description, File Size 

 

Pagination :  

Data table will contain pagination 

Pagination always enabled   

Pagination options:  

10 

25 

50 

100 

 

 

By default the data table should display the first 10 files  

 

Data table files will be organized by file name (alphanumeric order) 

 

User will have the ability to select/deselect all files on a page  

Deselect functionality will include a tool tip  

 

Data table will have a scroll functionality 

Data table will have a sort by ascending/ descending functionality for each column  

 

 
**File Name:** 

File names should be in the lower case format
ex. arp-initial-allocations
Refer to : [File name and description  ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B4b2dbba7-2970-40f9-a7ea-0294354e2020%7D) for file names 

**Date Updated:** 
Date will be displayed in the YYYY-MM-DD format 

**Descriptions:** 
The data table should display the full description name 
Refer to : [File name and description  ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?action=edit&sourcedoc=%7B4b2dbba7-2970-40f9-a7ea-0294354e2020%7D) for file descriptions 

 

 

 

**File Selection/ Download:**  

 

The system will display the number of file(s) a user has selected and the total file size  

 

User will have the ability to select and download multiple files 

No need for a Download manager. The system will generate multiple downloads  

 

 

Download functionality will be disabled until at least one file is selected  

 

If the number of files selected is greater than 50 gb (configurable limit) then the system will display an alert to notify the user that the number of files selected exceeds the download limit and the download functionality will be disabled

**Comment by JanellC** [comment]
@tlageman-epa 
Added requirements for the bulk data files that need to generated/ copied over from the FTP site. Need clarification on the following: 
1. If SMOKE data is in scope
2. When allowance/ compliance files should updated and how often the files need to be checked.

**Comment by JanellC** [comment]
[2:45 PM] Lageman, Travis
    Transactions - updated annually January 30th
​[2:45 PM] Lageman, Travis
    Compliance (both allowance & emissions) - updated annually June 30th
