### ISSUE TITLE
API for Allowance Holdings Data 

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#755]
PI 6 Estimate: 2

**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [x] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Has a clearly defined user
- [x] Has an estimate
- [x] Has acceptance criteria
- [x] Has sufficient context, such as

-User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)

- [x] Traceable to feature, epic or PI
- [x] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit

1. Provide Allowance Holdings data via API so the API returns all data needed for the EASEY Out Release

2. Validate Allowance Holdings API parameters to ensure that the request is valid

### Parameters

Public API Requirements

**Parameters**
QUESTION: 
Question: Should the system validate account number format? If so, what is the format? -12 alphanumeric, allow leading 0s, will search all account types (see below) 
Question: Should the system validate anything for the owner and/or operator? If so, what should be validated? In the business requirements you sent, you mentioned it should be validated like a facility. However, for facilities we are only validating ORIS code, and this seems like it would have different values that would require different validations. - Text string, not case sensitive, special characters allowed

**ASSUMPTIONS:**

Parameters will not be validated against each other (e.g. the system will not validate that Account name is valid for the ORIS code). The system will just return data for the parameters specified. 
Blank parameter values will return all records 
Query will be executed as an AND search (i.e. return only records that match all criteria)
API criteria inputs should not be case sensitive
API criteria inputs should accept white spaces before/after delimiters when multiple values inputted (e.g., “Facility A , Facility B”) 
Pagination should be optional for APIs

- Program: optional, multiple values allowed, active allowance only, values:  ARP, CSNOX, CSOSG1/2, CSSO2G1/2, TXSO2 
- Account Type: Optional, multiple values allowed, values: Facility Account, Unit Account, General Account, Reserve Account, Surrender Account, ALL (UI only)
- Account Number:  Optional, multiple values allowed, query will return all records that match Account Number  
- Facility: Optional, multiple values allowed, query will return all records that match Facility Name OR Facility Number (ORIS code)
- Owner/Operator: Optional, multiple values allowed, query will return all records that match owner OR operator specified 
- State: Optional, multiple values allowed, 2 letter postal abbreviation 
- Vintage Year: Optional, multi, Format: YYYY, 1995 or greater

[Account Type Group Codes.pdf](https://github.com/US-EPA-CAMD/easey-ui/files/6212987/Account.Type.Group.Codes.pdf)

### Validations

Program: 
1. Validate that the value matches a valid program 
Error Message: One or more  <   insert property > are not valid. Refer to the list of available <   insert property   > for valid values [ placeholder for link to endpoint ] FV-100

Account Type: 
1. Validate that the value matches a valid account type 
Value: Facility Account, Unit Account, General Account, Reserve Account, Surrender Account, ALL (UI Only) 

Error Message: Error Message: One or more <  insert property  > are not valid. Refer to the list of available <   insert property   > for valid values [ placeholder for link to endpoint  ] FV-100

Account Number:  
1. Validate that the account number is 12 alphanumeric characters long 

Error Message: Error Message: One or more <    insert property    > are not valid. Refer to the list of available <    insert property    > for valid values [   placeholder for link to endpoint   ] FV-100

Facility (ORIS Code) : 
1. Validate that the format is correct:

positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

Error Message: Error Message: One or more <    insert property    > are not valid. Refer to the list of available <   insert property    > for valid values [placeholder for link to endpoint] FV-100

Owner/Operator: 
1. No Validations 

State: 
1. Validate that value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC

Error Message: One or more states are not valid. Use the two letter postal abbreviation (use TX, not Texas). FV-101

Vintage Year: 
1. Validate that the date is in the format YYYY
2. Validate that all years are equal to or greater than 1995

Error Message: One or more <   insert property   > are not in the <   insert format   >. Ensure all <   insert property   > are in the <   insert format  > FV-102
Error Message: Update one or more <     insert property    > to <    insert valid range     > FV-105

 
Results
When the system identifies at least one record that matches the criteria, then for each record the system will display ordered by PRG_CODE > ACCOUNT_NUMER > VINTAGE_YEAR > START_BLOCK:
ACCOUNT_NUMBER
ACCOUNT_NAME
ORISPL_CODE
PRG_CODE
VINTAGE_YEAR
TOTAL_BLOCK
START_BLOCK
END_BLOCK
STATE
EPA_REGION (2 digit number)
OWN_DISPLAY
ACCOUNT_TYPE

## Context

[Background Doc ](https://teams.microsoft.com/l/file/68079845-C3BE-4AF2-AB42-F10929206BA1?tenantId=88b378b3-6748-4867-acf9-76aacbeca6a7&fileType=docx&objectUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam%2FShared%20Documents%2FGeneral%2FAnalysis%2C%20User%20Research%20and%20Design%2FAnalysis%2FEASEY%20Out%2FCAMPD%20Requirements_Allowance%20Holdings.docx&baseUrl=https%3A%2F%2Fusepa.sharepoint.com%2Fsites%2FCAMDCVPTeam&serviceName=teams&threadId=19:6f05dfa026c84672a2cc1bfa72c58f14@thread.skype&groupId=21a5e1cd-d3f1-48a6-801f-0d34e2d63d23)

**Comment by JorjaComer** [comment]
Split feature into API and filter sort. See #1009. Removed API from PI 4.

**Comment by JorjaComer** [comment]
From: Lageman, Travis
Sent: Wednesday, June 2, 2021 3:25 PM
To: jasonwhitehead@cvpcorp.com; sejaldhawan@cvpcorp.com; juniesenthilkumar@cvpcorp.com
Cc: Heese, Michael <Heese.Michael@epa.gov>
Subject: FW: Question about Owner/Operators in database

 

 

 

From: Mark Hayward <Mark.Hayward@erg.com>
Sent: Saturday, May 15, 2021 10:52 AM
To: Lageman, Travis <Lageman.Travis@epa.gov>; Ann Albrecht <Ann.Albrecht@erg.com>
Cc: Stetsyuk, Karina <Stetsyuk.Karina@epa.gov>; Gill, Sandeep <Gill.Sandeep@epa.gov>; Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: RE: Question about Owner/Operators in database

 

Travis,

 

Here is a summary of how AMPD currently populates owner/operator information for the reports.

 

I have also included details of the tables and data that store the owner/operator information. 

 

Let me know if you have additional questions, or would like to discuss further.

 

Mark

 

 

Account Info

Includes owners and operators are in separate columns
Populated from ACCOUNT_OWNER_DIM
Allowance Holdings

Includes owners and operators in a single column
Populated from ACCOUNT_FACT.OWN_DISPLAY
Using ACCOUNT_OWNER_DIM would allow for separation of owners and operators into separate columns
Allowance Transactions

Includes only owners (separate columns for transferor owners and transferee owners)
Populated from TRANSACTION_OWNER_DIM
Compliance (allowance based)

Includes owners and operators in separate columns
Populated from OWNER_DISPLAY_FACT
Compliance (emissions based)

Includes owners and operators in separate columns
Populated from OWNER_YEAR_DIM
Emissions (assuming same for hourly to annual?)

Includes owners and operators in separate columns
Populated from OWNER_YEAR_DIM
Facility Attributes

Includes owners and operators in separate columns
Populated from OWNER_YEAR_DIM
 

 

OWNER_YEAR_DIM:

Contains individual records for each unique combination of unit+year+owner+type
Includes all owners/operators active during the year
Data is used to populate OWNER_DISPLAY_FACT
Owners in OWN_DISPLAY
Operators in OPR_DISPLAY
Includes owners and operators linked to units in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
 

ACCOUNT_OWNER_DIM:

Contains individual records for each unique combination of account+program+owner+type
Includes all active owners/operators
Data is used to populate ACCOUNT_FACT.OWN_DISPLAY, including both owners and operators
For unit accounts
Includes owners/operators linked to the unit in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
For facility accounts
Includes owners/operators linked to any unit at the facility in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
Only loads program-specific records for programs active for the facility
Using data from ACCOUNT_PROGRAM_SS (CAMDBSP_CAMDAMS.ACCOUNT_PROGRAM)
For OTC/NBP accounts that are NOT unit accounts
Includes owners linked to the account in NTACCT_OWNER_SS (CAMDBSP_CAMDNATS.TACCT_OWNER)
May be companies or people
For all other accounts that are NOT unit or facility accounts
Includes owners linked to the account in ACCOUNT_OWNER_SS (CAMDBSP_CAMDAMS.ACCOUNT_OWNER)
May be companies or people
 

TRANSACTION_OWNER_DIM:

Contains individual records for each unique combination of transaction+program+account+owner+type
Includes only those owners/operators active on the transaction date
Data is used to populate TRANSACTION_FACT.BUY_OWN_DISPLAY_NAME and SELL_OWN_DISPLAY_NAME, including ONLY owners
For unit accounts
Includes owners linked to the unit in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
For facility accounts
Includes owners linked to any unit at the facility in UNIT_OWNER_SS (CAMDBSP_CAMD.UNIT_OWNER)
For OTC/NBP accounts that are NOT unit accounts
Includes owners linked to the account in NTACCT_OWNER_SS (CAMDBSP_CAMDNATS.TACCT_OWNER)
May be companies or people
For all other accounts that are NOT unit or facility accounts
Includes owners linked to the account in ACCOUNT_OWNER_SS (CAMDBSP_CAMDAMS.ACCOUNT_OWNER)
May be companies or people
 

 

From: Lageman, Travis <Lageman.Travis@epa.gov>
Sent: Wednesday, May 12, 2021 4:48 PM
To: Ann Albrecht <Ann.Albrecht@erg.com>; Mark Hayward <Mark.Hayward@erg.com>
Cc: Stetsyuk, Karina <Stetsyuk.Karina@epa.gov>; Gill, Sandeep <Gill.Sandeep@epa.gov>; Desantis, Laurel <Desantis.Laurel@epa.gov>
Subject: Question about Owner/Operators in database

 

CAUTION: Don't open links or attachments unless you recognize the sender and know they are safe.

Hi Mark and Ann,

 

In a recent review of data elements/tables in the database, we noticed there are multiple tables with owner/operator info. This gets a little confusing for allowance holdings information. For example, Allowance Holdings returns an “Owner” field but it contains both owner and operators, while all other AMPD datasets appear to have distinct “Owner” and “Operator” fields (although I’m not entirely sure about transactions if they also return just owner info or combine owner/operator and don’t specify that as in the holdings dataset).

 

Our goal is to use only distinct owner and operator fields in all the datasets we return in the new AMPD as opposed to a joined one like in Allowance Holdings. Could you help me understand the best place to pull this data from for each of the following datasets that contain owner and operator information? I recognize there may be some differences since emissions info is unit based whereas account info/compliance is facility/account based.

Account Info
Allowance Holdings
Allowance Transactions
Compliance (allowance based)
Compliance (emissions based)
Emissions (assuming same for hourly to annual?)
Facility Attributes
 

It may also be helpful to understand how the relevant owner/operator database tables you identified in the AMPD data dictionary relate to one another since they share a lot of the same owner/operator info, and often have the same data column name but tend to be formatted differently

Database Table Names: ACCOUNT_FACT, ACCOUNT_OWNER_DIM, OWNER_DISPLAY_FACT, OWNER_YEAR_DIM, TRANSACTION_OWNER_DIM, UNIT_COMPLIANCE_DIM, TRANSACTION_FACT
Data Column Names: OWN_DISPLAY, OPR_DISPLAY, BUY_OWN_DISPLAY_NAME, SELL_OWN_DISPLAY_NAME
 

Hope I made sense and that you can shed some light. Let me know if I can try to clarify further.

 

Thanks as always! I know you all have a lot with the RCU.

 

Best,

 

Travis Lageman

Environmental Policy Analyst

Clean Air Markets Division

U.S. Environmental Protection Agency

P: 202-564-0520

**Comment by JanellC** [comment]
Completed core functionality. The Allowance holdings api endpoint returns data and functions with validation.  
Removed Update MDM data labels to the new data dictionary #2089 from this epic.
