### ISSUE TITLE
Implement filter/sort for Apportioned Quarterly Emissions Data

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#777]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [x] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [x] Has a clearly defined user
- [x] Has an estimate
- [x] Has acceptance criteria
- [x] Has sufficient context, such as

- User research (not needed at this time)
- Screen Mockups/UI Design (time period panel)
- Data conversion (completed)
- system requirements are in progress 

- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
1.Provide Apportioned Quarterly Emissions data via API so the API returns all data needed for the EASEY Out Release

2.Validate Apportioned Quarterly Emissions API parameters to ensure that the request is valid

3.Provide front-end user interface to access Apportioned Quarterly Emissions data

## Context
[Refer to EASEY Out Production List ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc={ebc3fb4d-ba1e-45cb-ac7c-095db55470fd}&action=edit&wd=target%28MVP.one%7C614ec76c-68a2-4733-aba0-fec44a85f292%2FEASEY%20Out%20Production%20List%7Cc8cb4d3b-e98e-4a0c-9425-69e90352227d%2F%29)

## Apportioned Quarterly Emissions System Requirements 

Questions: 
1. How will the Years & Quarters  parameters function? Will this be similar to the year and months parameters  in the monthly emissions API? 

**Assumptions:** 

1. Parameters will not be validated against each other (e.g. the system will not validate that Account name is valid for the ORIS code). The system will just return data for the parameters specified. 

2. Blank parameter values will return all records

3. If multiple parameters are sent in a single query (TX, Coal), then only values that match all parameters will be returned (AND)

4. If multiple values are sent for a single parameter (e.g. TX, MD)  then all data that matches the values is returned (OR).

5. API criteria inputs should not be case sensitive

6. API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”) 

7. Pagination should be optional for APIs

8. The API will not accept facility name as filter criteria. It will only accept Facility ID (ORIS code). 

**API Parameters:** 
Years: Required, multiple values allowed, 1995-current quarter, Format: YYYY. Allow indiv. Years, ranges, and comma sep. list 
Quarters: Required, multiple values allowed, Format: 1,2,3,4 
Facility ID (Oris Code): Optional, multiple values allowed 
State: Optional, multiple values allowed, 2 letter postal abbreviation for the 50 states plus Puerto Rico.
Unit Type: Optional, multiple values allowed
Unit Fuel Type: Optional, multiple values allowed, query will filter on both primary and secondary fuel type 
Control Technologies: Optional, multiple values allowed
Program: Optional, multiple values allowed, excludes MATS

**UI Parameters**

**Data Type**
Button/drop down
Value: Emissions, Allowance, Compliance, default blank, 
Required
Single select 

**Data Sub-Type**
Drop down 
Value: Hourly Emissions, Daily Emissions, Monthly Emissions, Quarterly Emissions, Ozone Season Emissions, Annual Emissions, 
Facility/Unit Attributes, default blank
Required
Single select 

**Years:** 
Text field. Allows ranges and individual years (YYYY-YYYY, YYYY, YYYY)
Required, 
1995-current quarter, 
multiple values allowed,
Format: YYYY
Allow indiv. Years, ranges, and comma sep. list  (multiple 2019,2020, range 2017-2020, and indiv. Years 2015)

**Quarters:**
Design: TBD
Required, 
multiple values allowed, 
Format: 1,2,3,4 
Valid Rage: Quarter is equal to or less than the last reporting quarter 

**Facility** : 

**Facility Name**
Dynamic search
Search is a contains search
Results are displayed in Facility Name (ORIS Code)
Results populate in a list, parameters populates when a value is selected from the list  	(results list should stay at top of page/visible in current view, possible use pagination to keep window small)
Search is not case sensitive
Out of scope: If state is already selected, then search is limited to facilities in the selected state 	
Out of scope: If program is already selected, then facilities is limited to facilities associated to the selected program	
If no results are found, the system will indicate so. “No facilities match your search.”
Multi select 

**ORIS Code**	
Dynamic search
Search is a contains search
Results populate in a list, parameters populates when a value is selected from the list 
Results are displayed in Facility Name (ORIS Code) format
Out of scope: If state is already selected, then search is limited to facilities in the selected state 	
Out of scope: If program is already selected, then facilities is limited to facilities associated to the selected program
If no results are found, the system will indicate so. “No facilities match your search.”
Multi Select 

**State**: 

Dynamic search
Search is a “begins with” search
Results populate in a list, parameters populates when a value is selected from the list  	
Results display the full state name (Texas, not TX)
Out of scope: If Facility/ORIS Code is already selected, then state is automatically populated with the state (or states) associated to the facility(or facilities) 
Multi Select

**Unit Characteristics** 

**Unit Type**: 
Drop down
Values: Boiler, Turbine, default blank 
Optional
Multi select

- If boiler is selected, then the system displays a list of boiler unit types, multi select
- If a user selects All Boilers, then the system will show all boiler types are selected. 
- The system will provide the ability to select and deselect boiler types. 
- If turbine is selected, then the system displays a list of turbine unit types, multi select
- If a user selects All Turbines, than the system will show all turbine types are selected. 
- The system will provide the ability to select and deselect turbine types. - 

**Unit Fuel Type**: 

Drop down
Values: Coal, Gas, Oil, Other, default blank 
Optional
Multi select
Search is performed on Primary and Secondary fuel types  NOTE: Add "?" text to inform user this is how search works 
If coal is selected, then the system displays a list of coal fuel types, multi select
If gas is selected, then the system displays a list of gas fuel types, multi select
If oil is selected, then the system displays a list of oil fuel types, multi select

**Control Technologies:** 

Drop down
Values: SO2 Controls, Hg Controls, NOx Controls, PM Controls, default blank 
Optional
Multi Select 

**_Program_**	
Drop down, default blank
Values: All active and inactive programs (MATS is excluded)	
Optional
Multi select 
Out of scope: If facility is already selected, then programs is limited to programs associated to the selected facility 	

**Change Criteria**
The user will have the ability to clear one, many, or all filter criteria
If the user changes data type or sub data type, then:

The filter criteria displayed updates accordingly
No previously entered filter criteria is retained

If a user changes data type or sub data type, then filter criteria is cleared

If the user chooses to clear one or more filter criteria before preview is selected, then the system clears the criteria from the filter and updates any remaining dependent criteria accordingly.

If the user chooses to clear one or more filter criteria after preview is selected, then the system clears the criteria from the filter AND download is disabled until data is previewed.

**Validations**

**Year:**
Validate that at least one, value exists for the parameter
Validate that the date is in the format YYYY
Validate that the year is greater than or equal to 1995

Error Message 1: <insert property> should not be null or undefined FV-106 
Error Message 2: One or more <  insert property  > are not in the <  insert format  >. Ensure all <insert property> are in the <  insert format  > FV-102
Error Message 3: Update one or more <  insert property  > to <  insert valid range  > FV-105 
 
**Quarter:** 
Validate that at least one, value exists for the parameter
Validate that the date is in the format 1, 2, 3, or 4 
Validate that the quarter is equal to or less than the last reporting quarter 

Error Message 1: <insert property> should not be null or undefined FV-106 
Error Message 2: One or more <  insert property  > are not in the <  insert format  >. Ensure all <insert property> are in the <  insert format  > FV-102
Error Message 3:  TBD 

**Facility ID (Oris Code):** 

Validate that the value is a number 
If the value is a number, validate that the format is correct
positive integer (no negative numbers, not 0)
whole numeric value (no letters or special characters)
no more than 6 digits

Error Message:  One or more <    insert property    > are not valid. Refer to the list of available <     insert property     > for valid values [placeholder for link to endpoint] FV-100

**State:** 
Validate that the value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC

Error Message: One or more states are not valid. Use the two letter postal abbreviation (use TX, not Texas).  FV-101 

**Unit Type:** 
1. Validate that the value matches a valid unit type 

Error Message:  One or more <    insert property    > are not valid. Refer to the list of available <     insert property     > for valid values [placeholder for link to endpoint] FV-100

**Unit Fuel Type:** 
1. Validate that the value matches a valid fuel type 

Error Message:  One or more <    insert property    > are not valid. Refer to the list of available <     insert property     > for valid values [placeholder for link to endpoint] FV-100

**Control Technologies:**
1. Validate that the value matches a valid control technology 

Error Message:   One or more <    insert property    > are not valid. Refer to the list of available <     insert property     > for valid values [placeholder for link to endpoint] FV-100

**Program :** 

1. Validate that the value matches a valid program code

Error Message:  One or more <    insert property    > are not valid. Refer to the list of available <     insert property     > for valid values [placeholder for link to endpoint] FV-100

**Results:** 
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year > Quarter 
STATE
FACILITY_NAME
ORISPL_CODE
UNITID
ASSOC_STACKS
YEAR
QUARTER
SUM_OP_TIME
COUNT_OP_TIME
GLOAD
SLOAD
SO2_MASS
SO2_RATE
NOX_MASS
NOX_RATE
CO2_MASS
CO2_RATE
HEAT_INPUT
PRIMARY_FUEL_INFO
SECONDARY_FUEL_INFO
UNIT_TYPE_INFO
SO2_CONTROL_INFO
PART_CONTROL_INFO
NOX_CONTROL_INFO
HG_CONTROL_INFO
PRG_CODE_INFO

**UI**
New FC = 3 (0)
Existing FC = 1 (7)
Preview = 2
Filter Tags = 1
Download = 3

**API** 
8 points (includes CSV)
