### ISSUE TITLE
Implement filter/sort for MATS Data

### ISSUE THREAD

**Issue by JanellC** [US-EPA-CAMD/PI-1#801]
Original estimate: 40

## Feature Benefit

- [ ] Provide MATS via API endpoints. 
- [ ] Validate Hourly MATS API parameters to ensure that the request is valid
- [ ] Hourly Mats Data streaming endpoint
- [ ] Provide front-end user interface to access MATS data 
- [ ] Implement filter logic on the UI for MATS
- [ ] Add Data Caveat on MATS data: MATS required that coal-fired electricity generating units (EGUs) start reporting hourly MATS emissions and operations data as early as April 2015, but provided extensions for many EGUs until April 2016 or 2017. Therefore, complete MATS data are not available until calendar year 2018.  

### Assumptions  

1. Parameters will not be validated against each other (e.g. the system will not validate that Account name is valid for the ORIS code). The system will just return data for the parameters specified. 
2. Blank parameter will return all records 
3. If multiple parameters are sent in a single query (TX, Coal), then only values that match all parameters will be returned (AND) 
4.  If multiple values are sent for a single parameter (e.g. TX, MD) then all data that matches the values is returned (OR). 
5. API criteria inputs should not be case sensitive 
6. API criteria inputs should accept white spaces before/after delimiter when multiple values inputted (e.g., “Facility A , Facility B”) 
7. Non streaming Mats endpoint will require pagination. MATS streaming endpoint will not have pagination. 
8. Filter logic will be implemented for MATS Data on the CDD 
9. Aggregation is not needed for MATs data  
10. MATS Data will be made available via json and csv format  

 

### API Parameters  

- Begin Date: Required, Format: YYYY-MM-DD, single value, Valid date range: 01/01/2015- latest reporting quarter  
- End Date: Required, Format: YYYY-MM-DD, single value, Valid date range: 01/01/2015- latest reporting quarter 
- Operating Hours only: Optional, single value, values: true or false 
- State: Optional, multiple values allowed, 2 letter postal abbreviation 
- Facility ID (ORIS code): Optional, multiple values allowed 
- Unit Type: Optional, multiple values allowed  
- Unit Fuel Type: Optional, multiple values allowed  
- Control Technolgies: Optional, multiple values allowed 

 

### Custom Data Download  Requirements  

 

 **Data Type**  
Drop Down  
Value: Mercury and Air Toxics Emissions, default blank 
Required  
Single Select  

 

**Data Sub Type:**  
Drop down  
Value: Hourly Emissions 
Required  
Single Select  

 
**Time Period:**  
Date picker (USWDS date picker) 
Format: MM/DD/YYYY 
Required 
Valid date range: 01/01/2015- latest reporting quarter  
Operating hours only: selected by default  

 

**State/ Territory:**  
Optional  
Combo box 
Dynamic search 
Search is a “begins with” search 
Results populate in a list, parameters populates when a value is selected from the list 
Results display the full state name (Texas, not TX) 
Search is not case sensitive 
Multi Select   
 

**Facility:**  
Optional 
Combo box  
Dynamic search 
Contains search 
Results are displayed in Facility Name (ORIS Code) 
Results populate in a list, parameters populates when a value is selected from the list (results list should stay at top of page/visible in current view, possible use pagination to keep window small) 
Search is not case sensitive 
If no results are found, the system will indicate so. “No facilities match your search.” 
Multi select 

**Unit Type**  
Optional 
Check box component  
Values: Boilers, Turbines, Furnaces  \
Multi Select  

 

**Unit Fuel Type** 
Optional  
Check box component   
Values: Coal, Gas, Oil, Other  
Multi Select   

 
**Control Technology**  
OPTIONAL  
Check box component  
Values: SO2, NOX, PM, HG, other 
check box component 
Multi Select  

 

**Change Criteria** 
The user will have the ability to clear one, many, or all filter criteria 
If the user changes data type or sub data type, then: 

The filter criteria displayed updates accordingly 

No previously entered filter criteria is retained 

If a user changes data type or sub data type, then filter criteria is cleared 
If the user chooses to clear one or more filter criteria before preview is selected, then the system clears the criteria from the filter and updates any remaining dependent criteria accordingly. 
If the user chooses to clear one or more filter criteria after preview is selected, then the system clears the criteria from the filter AND download is disabled until data is previewed. 

 

 

**File Selection** 
Trigger: The user has at least one record that matches the search criteria, and has previewed the results 
The user has the option to select the file output in JSON or CSV format. CSV is the default file type 
Required 

 

 

**Download** 
Trigger: The user has selected a file output type 
When the user selects the option to download, the system creates a file in the format specified containing all records that match the parameters and downloads the file 
After a user has chosen to download data, then the system will display the preview of the downloaded results. 

 

 

### Filter Logic - need to talk to dev team  

For Emissions data: 

Time period will be required as the first selection 

Filter logic will narrow filter criteria based on time period and subsequent selections 

Filter criteria update dynamically as selections are made (upon Apply) 

Non applicable selections will be: 
*Removed from combo boxes 
*Grey out in check box lists 
 

If time period is deleted, then 
*the system displays a warning message 
*clears previously selected criteria 
*greys out all optional filters 

If years (in time period) are changed, then – needs confirmation from dev  
*the system displays a warning message (re: years) 
*clears previously selected criteria 

 

 

### Validations  

**Begin Date:**  
Validate that one and only one value exists for the parameter  
Validate that the date range is valid: 01/01/2015- latest reporting quarter 
Validate that the date is in the format: YYYY-MM-DD 

 

Error Message 1: <  insert property  > should not be null or undefined FV-106 

Error Message:  Ensure that  <  insert property  > is in the <insert format> FV-108  

Error Message: Update the <  insert property  > to <  insert valid range  > FV-104 

 

**End Date:**  
Validate that one and only one value exists for the parameter  
Validate that the date range is valid: 01/01/2015- latest reporting quarter 
Validate that the date is in the format: YYYY-MM-DD 
Validate End date is equal to or greater than start date 

 

Error Message 1: <  insert property  > should not be null or undefined FV-106 

Error Message: Ensure that  <insert property> is in the <insert format> FV-108  

Error Message: Error Message: Update the <  insert property  > to <  insert valid range  > FV-104  

Error Message Enter an <  insert property   > that is greater than or equal to the <  constraint  > FV-103 

 

**State:** 
Validate that the value matches a valid 2 letter postal abbreviation for at least 1 of the 50 states, PR, or DC 
Error Message: One or more states codes are not valid. Use the two letter postal abbreviation (use TX, not Texas). FV-101 

 

**Facility ID (ORIS Code):** 
Validate that the value is a number 
If the value is a number, validate that the format is correct 
positive integer (no negative numbers, not 0) 
whole numeric value (no letters or special characters) 
no more than 6 digits 

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100 

 

**Unit Type:**  
Validate that the value is a valid unit type. 

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100 

 

 

**Unit Fuel Type:**   
Validate that the value is a valid fuel type.  

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100 

 

**Control Technologies:**  

Validate that the value is a valid control technology.  

Error Message: One or more < insert property > are not valid. Refer to the list of available < insert property > for valid values [placeholder for link to endpoint] FV-100   

 

 

### Results 

When the system identifies at least one record that matches the criteria, then for each record the system will display ordered by: facilityId > unitId > date > hour 

The data labels will adhere to the [Master Data Dictionary.  ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BE47D193A-AD4E-491A-A2AC-6EFD4DB50FBC%7D&file=Final_CAMPD_Master%20Data%20Labels%20List_EPA%20CAMD_v1.0.xlsx&action=default&mobileredirect=true)

 

stateCode  

facilityName  

facilityId  

unitId  

date  

hour  

opTime  

matsGrossLoad  

matsHeatInput  

hgOutputRate  

hgInputRate  

hgMass  

hgMassMeasureFlg  

hclOutputRate  

hclInputRate  

hclMass  

hclMassMeasureFlg  

hfOutputRate  

hfInputRate  

hfMass  

hfMassMeasureFlg  

associatedStacks  

steamLoad  

primaryFuelInfo  

secondaryFuelInfo  

unitType  

so2ControlInfo  

noxControlInfo  

pmControlInfo  

hgControlInfo

**Comment by JanellC** [comment]
This epic will be completed for CAMPD release 2.0

**Comment by JanellC** [comment]
@tlageman-epa Updated the epic with the requirements discussed during the PD meeting today.

**Comment by JanellC** [comment]
Epic Complete
