### ISSUE TITLE
CAMPD Landing Page Concepts

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#814]
### Tasks
- [x] Gather resources and ideas for CAMPD landing page concepting and deliver to CVP (@areighar)
- [x] Develop possible landing page options, sharing ideas and concepts along the way (Alex)
- [x] Review concepts with BA and PO and approve a direction

### Assets
![CAMPD - Landing Page.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/370fde0e-fe4d-4f02-af48-82aef4ffc763)

### Stakeholders
@kstetsyuk @areighar @tlageman-epa @MoAdeyoju @JorjaComer

**Comment by tlageman-epa** [comment]
@cvp-alexrobinson  Please add the wireframe/screenshot links to the CAMPD landing page here for tracking. Thanks!

**Comment by cvp-alexrobinson** [comment]
@tlageman-epa — I've added the landing page image presented in the waiver meeting.
