### ISSUE TITLE
Business rules engine implementation

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#822]
**System Increment Definition of Ready (DoR)**
Before being accepted into a Program Increment each feature:

- [ ] Meets the INVEST criteria (Independent, Negotiable, Valuable, Estimate-able, Small, Testable)
- [ ] Has a clearly defined user
- [ ] Has an estimate
- [ ] Has acceptance criteria
- [ ] Has sufficient context, such as
- User Research 
- Wireframes/UI Design
- Data Conversion (completed)
- System Requirements (in progress)
- [ ] Traceable to feature, epic or PI
- [ ] Dependencies are identified
- [ ] Component reusability assessed

## Feature Benefit
Validate submitted data against EPA check specifications

## Context
BRE architectural diagram: https://github.com/US-EPA-CAMD/diagrams/blob/develop/EPA%20CAMD%20BRE%20Check%20Engine.pdf

### Outcome by end of PI4: 

- [ ] Figure out the structure of the table and storing rules for the database design model.
- [ ] Understand how engine works in queuing work and knowing how to pick up work. Understand order of magnitude for checks
- [ ] Figure out best way to populate source objects
- [ ] Figure out hierarchical structure of source objects and how to feed into rules
- [ ] Tool is purchased: confirmation that this will happen relatively soon. The license will be purchased under the ERG contract as EPA property.
- [ ] Work plan for loading rules (what rules get loaded, who is doing what)
- [ ] Create a design of the engine that will pull the data through the rules in the proper order.
- [ ] Set up the UI front-end to create rules, write them, and store them in a Postgres database.

**Comment by david-cvp** [comment]
Previous steps taken:

For discussion during Program Backlog Refinement (3/8/21) 
1. High-level timeline for BRE work in future PIs
2. When to engage with ERG and hold a kickoff meeting with them - confirmed that will be in the week of March 22.
3. When to obtain the BRE licenses

### Pre-Reqs:

1. Project kick off - CVP and EPA will have a meeting before the ERG kickoff meeting to determine agenda.
2. Determine scope for BRE - Dwayne will send an estimate for existing checks for Monitoring Plan by Friday 3/12.
3. ERG engagement plan - ERG engagement meeting will be scheduled for the week of March 22 (sprint 3.4). CVP and EPA will meet once before to determine agenda.

Outcome by end of I&P sprint before PI4:
1. Maintain an understanding of what the work will look like.

**Comment by MaeganWood64** [comment]
Epic no longer needed
