### ISSUE TITLE
Beta Release Readiness

### ISSUE THREAD

**Issue by nalcvp** [US-EPA-CAMD/PI-1#828]
## Feature Benefit
Track items needed for MP Beta Release 

- [ ] 1. Content for:

- Resources (FAQs Content and the updated Glossary)
- Help/Support (FAQs Content and CDX Help Topics)
- Regulatory Partners (Same links as CAMPD)
- Sitemap

- [ ] 2. ECMPS Quick Start Guide

- [ ] 3. Webinars under Tutorial

- [ ] 4. Dynamic Content:

- Updatable text block (EPA should be able to update) on ECMPS homepage. Ability to add text, links and to do special text such as bolding, italics etc in all the text blocks
- What's New Box (EPA should be able to update)
- Pre and Post Login Updatable text blocks, preference to have different content in each and also updatable by EPA

- [ ] 5. Notifications:

- Notifications from Updated Blog Posts
- For Submission Windows

- [ ] NFRs, Performnace Baseline

- [ ] Production Bug Tracking Process/Workflow

## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)
