### ISSUE TITLE
Add Aggregation to Emissions API Endpoints 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#859]
Original estimate: 21

## Documentation 

[AMPD Support - Aggregation Emissions Data ](https://usepa.sharepoint.com/:u:/r/sites/CAMDCVPTeam/Shared%20Documents/Datateers/3-Business%20Analysis/Requirements/AMPD%20Support%20-%20Aggregation%20of%20emissions%20data.msg?csf=1&web=1&e=5r6N6f)

## EPIC Benefit 

- [ ] Add an Aggregation parameter to each emissions API endpoint (excludes MATS) 

- [ ]  Add an aggregation parameter to each emissions streaming endpoint 

- [ ] Give users the ability to aggregate emissions data on the custom data download 

## Aggregation Requirements  

**Background:**  
Aggregation occurs as a simple sum for each pollutant mass at each time frame. For example, Facility A has 2 units (Unit 1 & Unit 2) that operate for each hour in a single day. Aggregating the hourly data for that day from Unit à Facility would sum each of Facility A’s units at each hour. 

The unit file has the hourly emissions data at the unit level. Changing the aggregation to the Facility level would just sum up the emissions data (each pollutant, gross load, steam load, and heat input) for each unit at each hour.

 
**Questions:**  
1. Will the streaming endpoints need an aggregation parameter? - Question for dev 

**Assumptions:**  
1. Aggregation will only be implemented for the following Emission sub types: hourly, daily, monthly, annual, quarterly, ozone. Aggregation is not applicable to allowance, compliance, facility, or MATS data   
2. Aggregation options are: “Unit” “Facility,” “State,” “National” 
3. An aggregation parameter will be  added to each emissions API endpoint (excludes MATs)  
4. API criteria inputs should not be case sensitive  

 
 

**Example Emissions Aggregation Files from AMPD:**  
1. [Hourly Emissions Unit Aggregation ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BC0966D06-AFA9-4489-96E8-D88F3904B9A7%7D&file=unit_emissions_ex.csv&action=default&mobileredirect=true)

2.[Hourly Emissions Facility Aggregation: ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BF77E188B-8C97-49BA-A2E4-82706C5652BE%7D&file=fac_emissions_ex.csv&action=default&mobileredirect=true)

**Annual Emissions** 
1. Unit Level Aggregation: [AnnualEmissions-UnitLevelAggregation-EPA CAMD-v1.0 ](https://usepa.sharepoint.com/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?OR=teams&action=edit&sourcedoc={9CA15121-6CCA-42CC-B4C5-091C269B2D0E})
2. Facility Level Aggregation: [AnnualEmissions-FacilityLevelAggregation-EPA CAMD-v1.0 ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7BBD836269-8B62-45B7-8454-B337EE220224%7D&file=AnnualEmissions-FacilityLevelAggregation-EPA%20CAMD-v1.0.csv&action=default&mobileredirect=true)
3. State Level Aggregation: [AnnualEmissions-StateLevelAggregation-EPACAMD-v1.0 ](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B3DBB0CE6-C265-48DF-831D-FE9586A0CC3A%7D&file=AnnualEmissions-StateLevelAggregation-EPACAMD-v1.0.csv&action=default&mobileredirect=true)
4. National Level Aggregation:[ AnnualEmissions-NationalLevelAggregation-EPA CAMD-v1.0](https://usepa.sharepoint.com/:x:/r/sites/CAMDCVPTeam/_layouts/15/Doc.aspx?sourcedoc=%7B74FBB11E-AAA2-45F2-9968-1B1778FDD23F%7D&file=AnnualEmissions-NationalLevelAggregation-EPA%20CAMD-v1.0.csv&action=default&mobileredirect=true) 

### API requirements (applicable to hourly, daily, monthly, annual, quarterly, ozone endpoints):   

Note: will need to create an aggregation endpoint for each aggregation level for each emissions sub type. Will not need an aggregation parameter or aggregation validations. 

**Parameters:**  
Aggregation: Required, Values: Unit, Facility, State, National, single value 

 
**Aggregation Parameter Validations:**  

1. Validate that one and only one value exists for the parameter 

2. Validate that the value is a valid aggregation value   

Error Message 1: <  insert property  > should not be null, undefined, or empty FV-106 

Error Message 2: <    insert value   > is not a valid aggregation value. Enter unit, facility, state, or national as a value. 
 

## UI Requirements 

**AGGREGATION:**  

Required  
Single value  
Values: Unit (No Aggregation), Facility, State, National 
Will display Unit (No Aggregation) by default 

**Change Criteria** - needs further discussion 
If a user applies filter  criteria and changes their aggregation selection then ..... 

   

Initial Aggregation wireframes: 
[Wireframes 
](https://xd.adobe.com/view/523c938e-a55c-4475-8eae-72d4b842cd0e-076f/)

### Hourly Emissions:  

**Unit Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display ordered by: facilityId > unitId > date > hour 

stateCode 

facilityName 

facilityId 

unitId 

associatedStacks 

date 

 hour 

opTime 

grossLoad 

steamLoad 

so2Mass 

so2MassMeasureFlg 

so2Rate 

so2RateMeasureFlg 

 co2Mass 

co2MassMeasureFlg 

co2Rate 

co2RateMeasureFlg 

noxMass 

noxMassMeasureFlg 

noxRate 

noxRateMeasureFlg 

heatInput 

primaryFuelInfo 

secondaryFuelInfo 

unitType 

so2ControlInfo 

 noxControlInfo 

 pmControlInfo 

 hgControlInfo 

programCodeInfo 

 

**Facility Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display ordered by: facilityId > date > hour

stateCode 

facilityName 

facilityId 

date 

hour 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

heatInput 

      

**State Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display ordered by:  State> date > hour

stateCode 

date 

hour 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

heatInput 

 

**National Aggregation:** 

When the system identifies at least one record that matches the criteria, then for each record the system will display ordered by:  date > hour

date 

hour 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

 heatInput 

 

  

### Daily Emissions 

**Unit Aggregation**  

For each record that matches the criteria, the system will display in a tabular format in the following order and ordered by Facility > Unit > Date 

stateCode 

facilityName 

facilityId 

unitId 

associatedStacks 

date 

sumOpTime 

countOpTime 

grossLoad 

steamLoad 

so2Mass 

so2Rate 

co2Mass 

co2Rate 

noxMass 

noxRate 

heatInput 

primaryFuelInfo 

 secondaryFuelInfo 

 unitType 

so2ControlInfo 

noxControlInfo 
pmControlInfo 

hgControlInfo 

programCodeInfo  

 

**Facility Aggregation**  

For each record that matches the criteria, the system will display in a tabular format in the following order and ordered by Facility  > Date

stateCode 

facilityName 

facilityId 
date 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

HeatInput 

 
**State Aggregation**  

For each record that matches the criteria, the system will display in a tabular format in the following order and ordered by State>  > Date 

 

stateCode 

 date 

grossLoad 

steamLoad 

so2Mass
 
co2Mass
 
noxMass 

 heatInput 

   

**National Aggregation**    
For each record that matches the criteria, the system will display in a tabular format in the following order and ordered by  Date 

date 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

heatInput 

 

 
### **Monthly Emissions**  

Unit Aggregation  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year > Month 

stateCode 

facilityName 

 facilityId 

 unitId 

 associatedStacks 

year 

month 

countOpTime 

sumOpTime 

grossLoad 

 steamLoad 

 so2Mass 

 so2Rate 

 co2Mass 

 co2Rate 

 noxMass 

 noxRate 

 heatInput 

 primaryFuelInfo 

 secondaryFuelInfo 

 unitType 

 so2ControlInfo 

 noxControlInfo 

 pmControlInfo 

 hgControlInfo 

 programCodeInfo 

 

**Facility Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Year > Month 

 stateCode 

 facilityName 

facilityId 

year 

month 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

 noxMass 

  heatInput 

   

State Aggregation  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by State> Year > Month 

stateCode 

year 

month 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

heatInput 

 

 

**National Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Year > Month 

year 

month 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

 noxMass 

 heatInput 

 

 

**Annual Emissions**  

**Unit Aggregation:**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year 

stateCode 

facilityName 

facilityId 

unitId 

associatedStacks 

year 

countOpTime 

sumOpTime 

grossLoad 

steamLoad 

 so2Mass 

 so2Rate, 

 co2Mass 

co2Rate 

noxMass 

noxRate 

heatInput 

primaryFuelInfo 

secondaryFuelInfo 

unitType 

so2ControlInfo 

noxControlInfo 

pmControlInfo 

hgControlInfo 

programCodeInfo 

 
**Facility Aggregation:**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Year 

stateCode 

facilityName 

facilityId 

year 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

 noxMass 

 heatInput 

     
**State Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by state> Year 

stateCode 

 year 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

 noxMass 

 heatInput 

 

**National Aggregation**  
When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Year 

year 

grossLoad 

 steamLoad 

 so2Mass 

co2Mass 

 noxMass 

 heatInput 

 

### Quarterly Emissions  

Unit Aggregation 

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year > Quarter  

stateCode 

 facilityName 

 facilityId 

 unitId 

 associatedStacks 

 year 

quarter 

countOpTime 

sumOpTime 

 grossLoad 

 steamLoad 

 so2Mass 

 so2Rate 

 co2Mass 

 co2Rate 

 noxMass 

 noxRate 

 heatInput 

 primaryFuelInfo 

 secondaryFuelInfo 

 unitType 

 so2ControlInfo 

 noxControlInfo 

 pmControlInfo 

 hgControlInfo 

 programCodeInfo 

 
**Facility Aggregation:**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Year > Quarter  

 stateCode 

 facilityName 

 facilityId 

 year 

quarter 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

noxMass 

heatInput 

  

**State Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by State> Year > Quarter  

stateCode 

 year 

 quarter 

 grossLoad 

 steamLoad 

 so2Mass 

 co2Mass 

 noxMass 

heatInput 

 

**National Aggregation** 

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by  Year > Quarter  

year 

quarter 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

 noxMass 

heatInput 

 

### Ozone Emissions 

**Unit Aggregation**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Unit > Year 

 
stateCode 

facilityName 

facilityId 

 unitId 

associatedStacks 

year 

countOpTime 

sumOpTime 

grossLoad 

steamLoad 

so2Mass 

 so2Rate 

 co2Mass 

 co2Rate 

noxMass 

noxRate 

heatInput 

primaryFuelInfo 

secondaryFuelInfo 

unitType 

so2ControlInfo 

 noxControlInfo 

 pmControlInfo 

 hgControlInfo 

 programCodeInfo 

 

**Facility Aggregation:**  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Facility > Year 

stateCode 

facilityName 

facilityId 

 year 

grossLoad 

steamLoad 

so2Mass 

co2Mass 

 noxMass 

 heatInput 

    

State Aggregation  

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by State> Year 

stateCode 

year 

grossLoad 

steamLoad 

 so2Mass 

 co2Mass 

 noxMass 

heatInput 

 

**National Aggregation** 

When the system identifies at least one record that matches the criteria, then for each record the system will display the data below and ordered by Year 

year 

grossLoad 

steamLoad 

 so2Mass 

 co2Mass 

 noxMass 

 heatInput

**Comment by JorjaComer** [comment]
Out of scope for May demo and possible release 1.0

**Comment by JorjaComer** [comment]
OBE

**Comment by JanellC** [comment]
@tlageman-epa For your review, I have transferred the aggregation requirements into this epic. I called out any initial questions that I have. We will continue to discuss the requirements during the Product Design meeting. Thanks.
