### ISSUE TITLE
Create Custom Data Download Data Type Selection 

### ISSUE THREAD

**Issue by JorjaComer** [US-EPA-CAMD/PI-1#883]
### Definition of Ready
- [x] Does this meet the INVEST criteria?
- [x] Does this have a clearly defined user?
- [x] Does this have an estimate?
- [x] Does this have acceptance criteria?
- [x] Does this have sufficient context (wireframes, business rules, etc.)?
- [x] Is this traceable to a feature, epic, or PI?

## User Story 
As a user I want to view custom data download options so that I can select my data type 

## Acceptance Criteria

Given I have navigated to the custom data download functionality
When the functionality is displayed
Then I have the option to select emissions, allowance, and compliance data

Given the user has selected a data type (emissions, allowance, or compliance)  
When they select continue
Then the filter criteria page is displayed (no content) 

Given a user has accessed the CAMPD custom data download functionality
When the application is displayed
Then it is displayed with a header

Given a user has accessed the CAMPD custom data download functionality in a lower (non-prod) environment
When the application is displayed
Then the system will indicate this is a sandbox (non-prod) environment

Given the updated header is displayed
When the menu option is chosen
Then the menu bar is displayed
And provides the option to close the menu 

Given a user has accessed the EPA header menu
When the menu is displayed
Then the following links are displayed(includes sub topic):

Environmental Topics
Laws & Regulations
About EPA
Given a user has selected a link from the header menu
When a link is selected
Then the system opens the link on the EPA website in a new tab

Given a user has chosen to search the EPA website via the header
When the search is executed
Then the system opens the link on the EPA website in a new tab to view the results

Given the updated footer is implemented
When the footer is displayed
Then it contains the EPA standard menu
And provides the ability to close the menu

Given a user has accessed the EPA menu
When the menu is displayed
Then the system displays the following links:

Accessibility
Privacy
Privacy and Security Notice
Given the menu is displayed
When a link is selected
Then the system opens the link on the EPA website in a new tab (see EPA.gov for links)

 ## Context
(User journeys, design mockups, architectural diagrams, business rules, data element definitions)

## Tasks
Set up Project:

- [x] Fork existing UI application
- [x]  Clean up UI application (remove non-applicable code)

## Testing
Test Case: [TC125](https://cvpcorp.testquality.com/project/11428/plan/20058/test/276468)
Tester: @davidkwartler 

### Definition of Done
- [x] Have all Acceptance Criteria been agreed to and validated by the scrum team?
- [x] Has the code been unit tested and peer reviewed?
- [x] Have the functional tests been executed?
- [x] Have all defects been reviewed and dispositioned, resolved, or deferred?
- [ ] Has the user story been accepted by the Product Owner?
- [x] Is the user story ready to be deployed to the test/staging environments?

**Comment by david-cvp** [comment]
Bug #1014 resolved

TC125 passed @tlageman-epa 

![image.png](https://images.zenhubusercontent.com/5efcffd55c24786a6456ee1b/63320fd0-d47a-42f4-acee-61dbac6bec36)
