### ISSUE TITLE
CAMPD Design Waiver Meeting Materials

### ISSUE THREAD

**Issue by cvp-alexrobinson** [US-EPA-CAMD/PI-1#892]
### 🧭 Objective
For the exemption template, we’re looking to present both the data type picker screen and the filter screen. We only need a snapshot of both screens. The only things we’re looking to add to the existing wireframes is the EPA logo in the top left corner, color, and breadcrumbs on the filter screen. No need to have the wireframe “working”. We’re mostly concerned on making the argument that we need to use a large amount of screen width, and a banner/header that won’t disrupt the breadcrumbs. We are still deciding on whether we want a compressed footer (similar to the ECMPS template), so please have snapshots with and without the footer on both screens (so four snapshots total). The compressed footer does not need to work.

### 📋 Tasks
- [x] Add EPA logo to existing wireframes
- [x] Add compressed footer placeholder to a new set of screens
- [x] Export four screens: datatype intro, datatype intro w/ footer, filters, filters w/ footer

### 🤝 Stakeholders
@kstetsyuk @tlageman-epa @MoAdeyoju @JorjaComer

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk @sgillEPA @tlageman-epa Here are four screens to use as talking points during the waiver discussion next week. Some things to note:
- I didn't include color on purpose. I didn't want to distract from the purpose of this waiver request with anything outside of grayscale wireframes.
- The header and footer (where applicable) have a fixed width, while the rest of the content on the Filters screens spans from edge to edge. This will hopefully make the case for the wide layout.
- The waiver documentation (below) is very clear about where there is wiggle room, and where EPA sites and web applications need to align with the EPA style guide and with USWDS. I'm sure you already have, but please take a look at the documentation.
  - [Applications and the One EPA Web Standalone Template](https://app.zenhub.com/files/287570343/354308b1-5251-4375-8820-dc14c05bf00c/download)
  - [Procedure: Complying with EPA.gov "Look andFeel"](https://app.zenhub.com/files/287570343/d6aec6e1-6b01-4eb9-8215-6b7ea852a47d/download)

![CDD - Intro.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/086c2b71-d745-48ed-9461-a1f4c77e6995)![CDD - Filters.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/51307ca7-5a85-4e07-94f7-b1a0521cb898)![CDD - Intro – Footer.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/6132ed94-551d-48c1-ae42-3beced98c071)![CDD - Filters – Footer.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/a808471f-e915-4fb4-9b04-2298da8d0cad)

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson Thanks for getting these to us! After talking with some folks, we'd like to have these snapshots in color (header, footer, and content). It would be helpful for when we are presenting these so we can show what our color scheme is, and what color buttons we plan on using, etc. The blue used on the regular epa.gov pages should work.
Let me know if you have any questions! Thanks!

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — Based on the Look and Feel documentation, really all you need—if anything at all—are grayscale wireframes. With that being said, I'm here to support you and the team with whatever you need so I've attached some colorized versions of the wireframes.

![CDD - Filters – Color.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/0f69b614-6103-4c33-aa10-f411b0d15fb5)![CDD - Filters – Footer – Color.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/0608db71-f37c-416c-8460-d49bd0b0d9ca)![CDD - Intro – Color.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/443f3b6e-eb6a-4033-b49b-6ff8be33f42d)![CDD - Intro – Footer – Color.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/02fd610a-5a41-462a-825e-38f31ed89541)

**Comment by cvp-alexrobinson** [comment]
**Landing Page and Data Preview Screens**
_Guidance from Karina, 3/17/2021:_
After some conversation, we need to refocus on materials for the Look & Feel waiver. It has come to our attention that a landing page would be huge aid in our justification, so we need something for that done as soon as possible. We are not looking for anything too complex – something simple that won’t take up much time. We just need to capture the basic idea of what that page will do/look like. We need these screenshots with the same header and footer as used in the “Custom Data Download” screenshots.

We also need a screenshot of the data preview for the “Custom Data Download” page. This will aid our argument that we need to use a wide area. Same header and footer. I will send you some dummy data later this afternoon.
 
We’d like to have these by COB tomorrow and can use ticket #892. If there are any questions, please let me know.

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — I still need to flesh out the preview data table, but am I getting close?

![CAMPD - Landing Page.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/41b25e36-4c5e-41be-a595-6fec75bb0728)![CAMPD - CDD - Intro.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/58eb113d-8f80-4ec1-8dbe-2faf70b8ee57)![CAMPD - CDD - Filters.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/556a906f-0307-4554-999e-148ca1549545)

**Comment by kstetsyuk** [comment]
Hey Alex,
Please use the same header/footer (colors) as in https://xd.adobe.com/view/e1a73023-0085-4e20-aa61-73e0e85cb064-b4f4/
Know it might be a bit awkward with colors, but maybe you have idea for an easy fix.
I'll pass the landing page to the team now to take a look. 
Thanks!

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson Sorry - scratch the previous message for color change. We'll keep this header and footer (the ones in the images you just posted) and see what Kevin has to say. Hoping it won't be too much hassle to change if need be?
Getting good feedback about the landing page, so at this point we just need the data preview.
Great work! Thanks again!

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — It's not difficult changing the header and footer, I just swap them out. But it sounds like we can stay with the light version for now. I'll keep working on the preview screen.

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — Here's the data preview screen. Let me know if this works.

![CAMPD - CDD - Filters – Data Preview.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/35db1034-b6f6-4e56-8fe2-ea0abc67d342)

**Comment by kstetsyuk** [comment]
@cvp-alexrobinson 
Here are some edits for the landing page.
•	Title: CAMPD: Clean Air Markets Program Data 
•	Remove top nav
•	Data: Create custom queries, download bulk datasets and use the CAMD API to retrieve CAMPD data.
•	Analysis *with “Coming Soon” disclaimer*: View and download common analyses, reports, insights and other information using CAMPD data. 
•	Viz *with “Coming Soon” disclaimer*: Visualize and interact with CAMPD data graphically and through maps.
Need “Coming Soon” because analysis and viz won’t be rolling that out in the first release.
Thanks!

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — The site navigation should always be present, no matter which page you're on. I understand that we've changed the architecture a bit though. I've updated the main navigation to be Home, Data, Analysis, and Visualization. Data, Analysis and Visualization would be drop downs that would house the other pages in that section. If for the demo tomorrow, you do want to remove the CAMPD navigation, please let me know.

Let me know if you have questions or concerns.

![CAMPD - Landing Page.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/87f65937-5575-4ee2-8e8d-a3154775a7fd)![CAMPD - CDD - Intro.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/4fa252b6-dd20-47a9-9ce3-a7b3ed9a0ba8)![CAMPD - CDD - Filters.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/86e646ef-e72a-44b8-94b1-efc0cf8e4dda)![CAMPD - CDD - Filters – Data Preview.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/b3027fe7-bd48-4425-a0ae-f5973c552909)

**Comment by cvp-alexrobinson** [comment]
@kstetsyuk — Here's the edit with no navigation:

![CAMPD - Landing Page.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/d28b6cfc-0c18-4fd4-b390-0a3e540a2cee)![CAMPD - CDD - Intro.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/07c40c0d-c841-47c7-98fb-636211931155)![CAMPD - CDD - Filters.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/ed52d209-fb5b-4a0d-a157-fd70d7a838b2)![CAMPD - CDD - Filters – Data Preview.png](https://images.zenhubusercontent.com/5f7481b4ffe2db3478776559/7bc8e854-77e3-4b77-871a-2189781ba253)
